// preload.js —— 通过 contextBridge 安全暴露 API 给渲染进程
const { contextBridge, ipcRenderer, webUtils } = require('electron');

contextBridge.exposeInMainWorld('myIDE', {
  remote: {
    ...Object.fromEntries(['load', 'save', 'remove', 'connect', 'disconnect', 'openTerminal', 'input', 'resize', 'ack', 'closeTerminal', 'list', 'mkdir', 'rename', 'removeFile', 'enqueue', 'cancel', 'retry', 'clearFinished', 'snapshot', 'localList', 'localMkdir', 'localRename', 'localRemove', 'forgetHost'].map(op => [op, (...args) => ipcRenderer.invoke('remote:' + op, ...args)])),
    onEvent: callback => { const listener = (_event, value) => callback(value); ipcRenderer.on('remote:event', listener); return () => ipcRenderer.removeListener('remote:event', listener); },
  },
  app: {
    getVersion: () => ipcRenderer.invoke('app:getVersion'),
  },
  // 本地设置镜像（容错）：localStorage 落盘失败时的兜底 —— 详见 main.js 里 SETTINGS_MIRROR 的注释
  settings: {
    probe: () => ipcRenderer.invoke('settings:probe'),
    mirrorWrite: (data) => ipcRenderer.invoke('settings:mirror-write', data),
    mirrorRead: () => ipcRenderer.invoke('settings:mirror-read'),
    // ⚠ 同步版：启动自愈必须在**任何模块读设置之前**完成（theme/tree/git-panel 在脚本加载期
    //   就读 localStorage），异步会晚一拍 → 表现为"主题先闪默认色再变回来"。
    mirrorReadSync: () => {
      try { return ipcRenderer.sendSync('settings:mirror-read-sync'); } catch { return { ok: false, data: null }; }
    },
  },
  quickLaunch: {
    load: () => ipcRenderer.invoke('quick-launch:load'),
    save: (config, version) => ipcRenderer.invoke('quick-launch:save', config, version),
    open: (id, version) => ipcRenderer.invoke('quick-launch:open', id, version),
    icon: (id, target) => ipcRenderer.invoke('quick-launch:icon', id, target),
    pick: (type) => ipcRenderer.invoke('quick-launch:pick', type),
    previewImport: (kind, groupId) => ipcRenderer.invoke('quick-launch:import', kind, groupId),
    applyImport: (token, selection) => ipcRenderer.invoke('quick-launch:applyImport', token, selection),
    cancelImport: (token) => ipcRenderer.invoke('quick-launch:cancelImport', token),
    export: () => ipcRenderer.invoke('quick-launch:export'),
  },
  tasks: {
    inspect: (project) => ipcRenderer.invoke('tasks:inspect', project),
    list: (project) => ipcRenderer.invoke('tasks:list', project),
    read: (project, id) => ipcRenderer.invoke('tasks:read', project, id),
    save: (project, raw, expectedVersion, onlyLocal) => ipcRenderer.invoke('tasks:save', project, raw, expectedVersion, onlyLocal),
    restore: (project, id, expectedVersion) => ipcRenderer.invoke('tasks:restore', project, id, expectedVersion),
    exportCopy: (project, id, target) => ipcRenderer.invoke('tasks:exportCopy', project, id, target),
  },
  fs: {
    openFolder: () => ipcRenderer.invoke('fs:openFolder'),
    pickImage: () => ipcRenderer.invoke('fs:pickImage'),
    pickFile: (title, filters) => ipcRenderer.invoke('fs:pickFile', title, filters),
    pickSave: (title, defaultName, filters) => ipcRenderer.invoke('fs:pickSave', title, defaultName, filters),
    getRecent: () => ipcRenderer.invoke('fs:getRecent'),
    setRecent: (p) => ipcRenderer.invoke('fs:setRecent', p),
    inspectDirectory: (p) => ipcRenderer.invoke('fs:inspectDirectory', p),
    readDir: (p, showHidden) => ipcRenderer.invoke('fs:readDir', p, showHidden),
    listAll: (p, showHidden) => ipcRenderer.invoke('fs:listAll', p, showHidden),
    grep: (p, q) => ipcRenderer.invoke('fs:grep', p, q),
    search: (request) => ipcRenderer.invoke('fs:search', request),
    cancelSearch: (requestId) => ipcRenderer.invoke('fs:search-cancel', requestId),
    onSearchBatch: (cb) => { const listener = (_e, batch) => cb(batch); ipcRenderer.on('fs:search-batch', listener); return () => ipcRenderer.removeListener('fs:search-batch', listener); },
    readFile: (p, enc) => ipcRenderer.invoke('fs:readFile', p, enc),
    readBuffer: (p) => ipcRenderer.invoke('fs:readBuffer', p),
    // 拖进来的文件取真实路径：Electron 32+ 移除了 File.path，只能走 webUtils.getPathForFile
    pathOfDroppedFile: (file) => { try { return webUtils.getPathForFile(file) || ''; } catch { return ''; } },
    fileVersion: (p) => ipcRenderer.invoke('fs:fileVersion', p),
    writeFile: (p, c, enc, condition) => ipcRenderer.invoke('fs:writeFile', p, c, enc, condition),
    writeBinary: (p, b64) => ipcRenderer.invoke('fs:writeBinary', p, b64),
    mkdir: (p) => ipcRenderer.invoke('fs:mkdir', p),
    createItem: (project, parent, name, type) => ipcRenderer.invoke('fs:createItem', project, parent, name, type),
    undoCreate: (project, p, after) => ipcRenderer.invoke('fs:undoCreate', project, p, after),
    copyPrepare: (project, sources, dest) => ipcRenderer.invoke('fs:copyPrepare', project, sources, dest),
    copyCommit: (project, id, overwrite) => ipcRenderer.invoke('fs:copyCommit', project, id, overwrite),
    copyUndo: (project, id) => ipcRenderer.invoke('fs:copyUndo', project, id),
    deletePrepare: (project, sources) => ipcRenderer.invoke('fs:deletePrepare', project, sources),
    deleteCommit: (project, id) => ipcRenderer.invoke('fs:deleteCommit', project, id),
    deleteUndo: (project, id) => ipcRenderer.invoke('fs:deleteUndo', project, id),
    trashPlan: (project, sources) => ipcRenderer.invoke('fs:trashPlan', project, sources),
    trashCommit: (project, plan) => ipcRenderer.invoke('fs:trashCommit', project, plan),
    copyList: (project) => ipcRenderer.invoke('fs:copyList', project),
    copyExport: (project, id) => ipcRenderer.invoke('fs:copyExport', project, id),
    copyClear: (project, id) => ipcRenderer.invoke('fs:copyClear', project, id),
    copyOpen: (id) => ipcRenderer.invoke('fs:copyOpen', id),
    pathSnapshot: (p) => ipcRenderer.invoke('fs:pathSnapshot', p),
    relocate: (p, target, condition) => ipcRenderer.invoke('fs:relocate', p, target, condition),
    rename: (p, n, condition) => ipcRenderer.invoke('fs:rename', p, n, condition),
    move: (src, destDir, condition) => ipcRenderer.invoke('fs:move', src, destDir, condition),
    remove: (p) => ipcRenderer.invoke('fs:remove', p),
    watch: (p) => ipcRenderer.invoke('fs:watch', p),
    onChanged: (cb) => ipcRenderer.on('fs:changed', (_e, info) => cb(info)),
  },
  log: {
    write: (level, tag, msg) => ipcRenderer.invoke('log:write', level, tag, msg),
  },
  shell: {
    showInFolder: (p) => ipcRenderer.invoke('shell:showInFolder', p),
    openExternal: (url) => ipcRenderer.invoke('shell:openExternal', url),
    openTerminal: (dir) => ipcRenderer.invoke('shell:openTerminal', dir),
    runFile: (p) => ipcRenderer.invoke('run:file', p),
    runCode: (code, lang) => ipcRenderer.invoke('run:code', code, lang),
  },
  win: {
    minimize: () => ipcRenderer.invoke('win:minimize'),
    toggleMaximize: () => ipcRenderer.invoke('win:toggleMaximize'),
    close: () => ipcRenderer.invoke('win:close'),
    isMaximized: () => ipcRenderer.invoke('win:isMaximized'),
    zoom: (dir) => ipcRenderer.invoke('win:zoom', dir), // 1 放大 / -1 缩小 / 0 重置（编辑器内 Ctrl+± 为代码折叠）
    onZoom: (cb) => ipcRenderer.on('ui:zoom', (_e, z) => cb(z)), // 整窗缩放变化（浏览器等原生视图需重算 bounds）
  },
  clip: {
    copy: (t) => ipcRenderer.invoke('clip:copy', t),
    copyFiles: (paths, move) => ipcRenderer.invoke('clip:copyFiles', paths, move),
    getFiles: () => ipcRenderer.invoke('clip:getFiles'),
    readText: () => ipcRenderer.invoke('clip:readText'),
  },
  fsCopy: (src, destDir, overwrite) => ipcRenderer.invoke('fs:copy', src, destDir, overwrite),
  checkConflict: (srcPaths, destDir) => ipcRenderer.invoke('fs:checkExists', srcPaths, destDir),
  git: {
    init: (d) => ipcRenderer.invoke('git:init', d),
    status: (d, options) => ipcRenderer.invoke('git:status', d, options),
    log: (d, depth, ref) => ipcRenderer.invoke('git:log', d, depth, ref),
    logGraph: (d, limit, ref) => ipcRenderer.invoke('git:logGraph', d, limit, ref),
    commit: (d, o) => ipcRenderer.invoke('git:commit', d, o),
    diffWorkdir: (d, f) => ipcRenderer.invoke('git:diffWorkdir', d, f),
    // M3：双区差异 + hunk 级暂存（idx = 该 diff 里第几块）
    diffUnstaged: (d, f) => ipcRenderer.invoke('git:diffUnstaged', d, f),
    diffStaged: (d, f) => ipcRenderer.invoke('git:diffStaged', d, f),
    stageHunk: (d, f, selection) => ipcRenderer.invoke('git:stageHunk', d, f, selection),
    unstageHunk: (d, f, selection) => ipcRenderer.invoke('git:unstageHunk', d, f, selection),
    revertHunk: (d, f, selection) => ipcRenderer.invoke('git:revertHunk', d, f, selection),
    diffCommit: (d, oid, f) => ipcRenderer.invoke('git:diffCommit', d, oid, f),
    compareRefs: (d, a, b) => ipcRenderer.invoke('git:compareRefs', d, a, b),
    diffRefs: (d, a, b, f) => ipcRenderer.invoke('git:diffRefs', d, a, b, f),
    commitFiles: (d, oid) => ipcRenderer.invoke('git:commitFiles', d, oid),
    branches: (d) => ipcRenderer.invoke('git:branches', d),
    checkout: (d, ref) => ipcRenderer.invoke('git:checkout', d, ref),
    createBranch: (d, name) => ipcRenderer.invoke('git:createBranch', d, name),
    // M4：分支工作流 / 冲突解决（原生 git；无本机 git 时返回值带 error，UI 按 caps 隐藏入口）
    opState: (d) => ipcRenderer.invoke('git:opState', d),
    merge: (d, ref, o) => ipcRenderer.invoke('git:merge', d, ref, o),
    rebase: (d, ref) => ipcRenderer.invoke('git:rebase', d, ref),
    conflicts: (d) => ipcRenderer.invoke('git:conflicts', d),
    conflictSides: (d, f) => ipcRenderer.invoke('git:conflictSides', d, f),
    resolveFile: (d, f, side) => ipcRenderer.invoke('git:resolveFile', d, f, side),
    continueOp: (d) => ipcRenderer.invoke('git:continueOp', d),
    skipOp: (d) => ipcRenderer.invoke('git:skipOp', d),
    abortOp: (d) => ipcRenderer.invoke('git:abortOp', d),
    branchCreate: (d, name, ref, co) => ipcRenderer.invoke('git:branchCreate', d, name, ref, co),
    branchRename: (d, from, to) => ipcRenderer.invoke('git:branchRename', d, from, to),
    branchDelete: (d, name, force) => ipcRenderer.invoke('git:branchDelete', d, name, force),
    resolveCustom: (d, f, text) => ipcRenderer.invoke('git:resolveCustom', d, f, text),
    readWorktreeText: (d, f) => ipcRenderer.invoke('git:readWorktreeText', d, f),
    pushForceWithLease: (d, remote, branch) => ipcRenderer.invoke('git:pushForceWithLease', d, remote, branch),
    setUpstream: (d, ref) => ipcRenderer.invoke('git:setUpstream', d, ref),
    unsetUpstream: (d) => ipcRenderer.invoke('git:unsetUpstream', d),
    precommitRun: (d, o) => ipcRenderer.invoke('git:precommitRun', d, o),
    scanTodo: (d, files, kinds) => ipcRenderer.invoke('git:scanTodo', d, files, kinds),
    discard: (d, f) => ipcRenderer.invoke('git:discard', d, f),
    discardFiles: (d, files) => ipcRenderer.invoke('git:discardFiles', d, files),
    getUserConfig: (d) => ipcRenderer.invoke('git:getUserConfig', d),
    setUserConfig: (d, cfg) => ipcRenderer.invoke('git:setUserConfig', d, cfg),
    // 远程 / 标签 / 还原 / 文件历史 / blame
    listRemotes: (d) => ipcRenderer.invoke('git:listRemotes', d),
    addRemote: (d, cfg) => ipcRenderer.invoke('git:addRemote', d, cfg),
    removeRemote: (d, name) => ipcRenderer.invoke('git:removeRemote', d, name),
    fetch: (d, opts) => ipcRenderer.invoke('git:fetch', d, opts),
    pull: (d, opts) => ipcRenderer.invoke('git:pull', d, opts),
    push: (d, opts) => ipcRenderer.invoke('git:push', d, opts),
    listPushCommits: (d) => ipcRenderer.invoke('git:listPushCommits', d),
    shelveCreate: (d, cfg) => ipcRenderer.invoke('git:shelveCreate', d, cfg),
    shelveList: (d) => ipcRenderer.invoke('git:shelveList', d),
    shelveApply: (d, id, opts) => ipcRenderer.invoke('git:shelveApply', d, id, opts),
    shelveDelete: (d, id) => ipcRenderer.invoke('git:shelveDelete', d, id),
    aheadBehind: (d, opts) => ipcRenderer.invoke('git:aheadBehind', d, opts),
    listTags: (d) => ipcRenderer.invoke('git:listTags', d),
    createTag: (d, cfg) => ipcRenderer.invoke('git:createTag', d, cfg),
    revert: (d, oid) => ipcRenderer.invoke('git:revert', d, oid),
    cherryPick: (d, oid) => ipcRenderer.invoke('git:cherryPick', d, oid),
    logFile: (d, file, limit) => ipcRenderer.invoke('git:logFile', d, file, limit),
    blame: (d, file) => ipcRenderer.invoke('git:blame', d, file),
    addToGitignore: (d, file) => ipcRenderer.invoke('git:addToGitignore', d, file),
    removeFromGitignore: (d, file) => ipcRenderer.invoke('git:removeFromGitignore', d, file),
    listIgnored: (d) => ipcRenderer.invoke('git:listIgnored', d),
    // 原生 git 后端（M2）：能力探测 / 测试候选路径（只读）/ 保存路径（写 ~/.myide/git-native.json）
    backendInfo: (force) => ipcRenderer.invoke('git:backendInfo', force),
    testGitExe: (cand) => ipcRenderer.invoke('git:testGitExe', cand),
    setGitExe: (p) => ipcRenderer.invoke('git:setGitExe', p),
  },
  plugins: {
    loadAll: () => ipcRenderer.invoke('plugins:loadAll'),
    onChanged: (cb) => ipcRenderer.on('plugins:changed', () => cb()),
  },
  llm: {
    // OpenAI 兼容对话（翻译插件用）：cfg={baseUrl, apiKey, model}
    chat: (cfg, messages) => ipcRenderer.invoke('llm:chat', cfg, messages),
  },
  launch: {
    config: () => ipcRenderer.invoke('launch:config'),
    save: (cfg) => ipcRenderer.invoke('launch:save', cfg),
    import: (p) => ipcRenderer.invoke('launch:import', p),
    paths: () => ipcRenderer.invoke('launch:paths'),
    addOrigin: (o) => ipcRenderer.invoke('launch:origin-add', o),
    removeOrigin: (o) => ipcRenderer.invoke('launch:origin-remove', o),
    start: (e) => ipcRenderer.invoke('launch:start', e),
    stop: (e) => ipcRenderer.invoke('launch:stop', e),
    restart: (e) => ipcRenderer.invoke('launch:restart', e),
    status: (entries) => ipcRenderer.invoke('launch:status', entries),
    alive: (e) => ipcRenderer.invoke('launch:alive', e),
    logs: (id) => ipcRenderer.invoke('launch:logs', id),
    clearLogs: (id) => ipcRenderer.invoke('launch:clear-logs', id),
    portCheck: (p) => ipcRenderer.invoke('launch:port-check', p),
    openUrl: (u) => ipcRenderer.invoke('launch:open-url', u),
    getKeep: () => ipcRenderer.invoke('launch:get-keep'),
    setKeep: (v) => ipcRenderer.invoke('launch:set-keep', v),
  },
  ai: {
    ...(process.argv.includes('--ai-approval-test') ? { testing: { snapshot: () => ipcRenderer.invoke('ai:testApprovalSnapshot'), click: (id,selector) => ipcRenderer.invoke('ai:testApprovalClick',id,selector) } } : {}),
    // AI 助手流式对话：chunk/done 事件推送；abort 中断生成；tools = 原生 function calling
    chat: (cfg, messages, tools, context) => ipcRenderer.invoke('ai:chat', cfg, messages, tools, context),
    abort: (context) => ipcRenderer.invoke('ai:abort', context),
    finish: (context) => ipcRenderer.invoke('ai:finish', context),
    validateTool: (context, call) => ipcRenderer.invoke('ai:validateTool', context, call),
    permissions: root => ipcRenderer.invoke('ai:permissions', root),
    updatePermissions: (root, config) => ipcRenderer.invoke('ai:updatePermissions', root, config),
    forgetPermission: (root, key) => ipcRenderer.invoke('ai:forgetPermission', root, key),
    authorize: (context, call) => ipcRenderer.invoke('ai:authorize', context, call),
    grantSession: context => ipcRenderer.invoke('ai:grantSession', context),
    clearSession: () => ipcRenderer.invoke('ai:clearSession'),
    onPermissionsChanged: callback => ipcRenderer.on('ai:permissionsChanged', (_event, view) => callback(view)),
    onStopped: callback => ipcRenderer.on('ai:stopped', (_event, context) => callback(context)),
    readFile: (context, call) => ipcRenderer.invoke('ai:readFile', context, call),
    readDir: (context, call) => ipcRenderer.invoke('ai:readDir', context, call),
    search: (context, call) => ipcRenderer.invoke('ai:search', context, call),
    writeFile: (context, p, content, format, condition, call) => ipcRenderer.invoke('ai:writeFile', context, p, content, format, condition, call),
    run: (cmd, cwd, context, call) => ipcRenderer.invoke('ai:run', cmd, cwd, context, call),
    onChunk: (cb) => ipcRenderer.on('ai:chunk', (_e, delta) => cb(delta)),
    onDone: (cb) => ipcRenderer.on('ai:done', (_e, r) => cb(r)),
  },
  browser: {
    // WebContentsView 内置浏览器（主进程管理，规避 <webview> guest 视口高度同步失效）
    viewOpen: (url) => ipcRenderer.invoke('browser:view-open', url),
    viewBounds: (rect) => ipcRenderer.invoke('browser:view-bounds', rect),
    viewHide: () => ipcRenderer.invoke('browser:view-hide'),
    viewNav: (cmd) => ipcRenderer.invoke('browser:view-nav', cmd), // back/forward/reload/focus
    // 网页深色模式：主进程 nativeTheme.themeSource（'dark'|'light'|'system'）。
    // 是进程级的 —— 网页里的 prefers-color-scheme 跟着变，本 IDE 自己的界面不受影响
    // （styles.css 里没有任何 prefers-color-scheme 规则，主题由 body.theme-* 显式决定）
    setColorScheme: (mode) => ipcRenderer.invoke('browser:color-scheme', mode),
    // 主进程转发的 view 内导航快捷键命令（toggle/back/forward/reload/focus-url）
    onCmd: (cb) => ipcRenderer.on('browser:cmd', (_e, cmd) => cb(cmd)),
    // 主进程推送的页面状态（url/title/loading/canBack/canFwd/progress/err）
    onState: (cb) => ipcRenderer.on('browser:state', (_e, s) => cb(s)),
  },
  appInfo: () => ipcRenderer.invoke('app:info'),
  db: {
    // 数据库工具（MySQL / SQLite）：cfg 含密码，只在主进程内存中流转
    connect: (cfg) => ipcRenderer.invoke('db:connect', cfg),
    close: (id) => ipcRenderer.invoke('db:close', id),
    tables: (id) => ipcRenderer.invoke('db:tables', id),
    columns: (id, table) => ipcRenderer.invoke('db:columns', id, table),
    select: (id, table, page, size) => ipcRenderer.invoke('db:select', id, table, page, size),
    query: (id, sql, params) => ipcRenderer.invoke('db:query', id, sql, params),
    updateCell: (id, table, pk, pkVals, col, val) => ipcRenderer.invoke('db:updateCell', id, table, pk, pkVals, col, val),
    deleteRows: (id, table, pk, pkRows) => ipcRenderer.invoke('db:deleteRows', id, table, pk, pkRows),
    insertRow: (id, table, cols, vals) => ipcRenderer.invoke('db:insertRow', id, table, cols, vals),
    ddl: (id, table) => ipcRenderer.invoke('db:ddl', id, table),
    er: (id) => ipcRenderer.invoke('db:er', id),
    explain: (id, sql) => ipcRenderer.invoke('db:explain', id, sql),
    exportCsv: (id, table, filePath, format) => ipcRenderer.invoke('db:exportCsv', id, table, filePath, format),
    importCsv: (id, table, filePath) => ipcRenderer.invoke('db:importCsv', id, table, filePath),
  },
});
