const assert=require('assert/strict'),{EventEmitter}=require('events'),path=require('path'),{pathToFileURL}=require('url');
const {createUI}=require('../ai-approval-ui');let passed=0;
const test=async(name,fn)=>{await fn();passed++;console.log('  ok '+name);};
function fixture(){
  const handlers=new Map(),views=[];let stopped=0;
  const win=new EventEmitter();Object.assign(win,{webContents:{},contentView:{addChildView(){},removeChildView(){}},getContentSize:()=>[800,600],isDestroyed:()=>false,isVisible:()=>false});
  class View{constructor(options){this.options=options;const wc=new EventEmitter();this.webContents=wc;Object.assign(wc,{mainFrame:{},isDestroyed:()=>!!wc.closed,close:()=>{wc.closed=true;wc.emit('destroyed');},setWindowOpenHandler:fn=>wc.windowOpen=fn,getURL:()=>pathToFileURL(path.join(__dirname,'../renderer/ai-approval.html')).href,loadFile:async()=>{},send:(name,data)=>{wc.data=data;},focus:()=>{throw Error('hidden focus');}});views.push(this);}setBounds(b){this.bounds=b;}}
  const ui=createUI({ipcMain:{handle:(name,fn)=>handlers.set(name,fn)},WebContentsView:View,getWindow:()=>win,stopRequest:()=>stopped++});
  const data={owner:1,context:{requestId:'one'},effect:{kind:'write'},call:{id:'one'}};
  const start=async()=>{const controller=new AbortController(),promise=ui.confirm(data,controller.signal);await new Promise(r=>setImmediate(r));const view=views.at(-1),event={sender:view.webContents,senderFrame:view.webContents.mainFrame};return {controller,promise,view,event};};
  return {ui,win,data,start,handlers,stopped:()=>stopped};
}
(async()=>{
  await test('宿主/陌生页面/子frame/未知nonce不能批准，真实独立页面才能结束',async()=>{const f=fixture(),s=await f.start(),answer=f.handlers.get('ai-approval:answer'),id=s.view.webContents.data.id;for(const [event,nonce]of [[{...s.event,sender:{}},id],[{...s.event,senderFrame:{}},id],[s.event,'fake']])assert.equal(answer(event,nonce,{approved:true,scope:'once'}).errorCode,'INVALID_AI_APPROVAL_SENDER');assert(!s.view.webContents.closed);assert(answer(s.event,id,{approved:true,scope:'once'}).ok);assert.deepEqual(await s.promise,{approved:true,scope:'once'});assert(s.view.webContents.closed);assert.equal(answer(s.event,id,{approved:true,scope:'once'}).errorCode,'INVALID_AI_APPROVAL_SENDER');});
  await test('危险操作不能选永久范围，策略/会话确认也只接受一次选择',async()=>{for(const type of ['operation','policy','session']){const f=fixture();let controller=new AbortController();const promise=f.ui.open({...f.data,type,danger:true},controller.signal);await new Promise(r=>setImmediate(r));controller.abort();await assert.rejects(promise,e=>e.code==='CANCELLED_AI_REQUEST');}const f=fixture();f.data.danger=true;const s=await f.start(),answer=f.handlers.get('ai-approval:answer'),id=s.view.webContents.data.id;assert.equal(answer(s.event,id,{approved:true,scope:'project'}).errorCode,'INVALID_AI_APPROVAL');answer(s.event,id,{approved:false,scope:'once'});assert.equal((await s.promise).approved,false);});
  await test('abort、窗口关闭、页面跳转和崩溃都取消；旧按钮不能复活',async()=>{for(const trigger of [s=>s.controller.abort(),(s,f)=>f.win.emit('close'),s=>s.view.webContents.emit('will-navigate',{preventDefault(){}}),s=>s.view.webContents.emit('render-process-gone')]){const f=fixture(),s=await f.start();trigger(s,f);await assert.rejects(s.promise,e=>e.code==='CANCELLED_AI_REQUEST');assert(s.view.webContents.closed);assert.equal(f.win.listenerCount('resize'),0);}});
  await test('可信停止按钮终止所属任务，宿主伪造停止不能触发',async()=>{const f=fixture(),s=await f.start(),stop=f.handlers.get('ai-approval:stop'),id=s.view.webContents.data.id;assert.equal(stop({...s.event,sender:{}},id).errorCode,'INVALID_AI_APPROVAL_SENDER');assert.equal(f.stopped(),0);assert(stop(s.event,id).ok);await assert.rejects(s.promise,e=>e.code==='CANCELLED_AI_REQUEST');assert.equal(f.stopped(),1);});
  await test('独立视图隔离参数与隐藏模式、窗口缩小后的边界',async()=>{const f=fixture(),s=await f.start();assert(s.view.options.webPreferences.sandbox);assert(s.view.options.webPreferences.contextIsolation);assert(!s.view.options.webPreferences.nodeIntegration);assert(!s.view.options.webPreferences.partition.startsWith('persist:'));assert.equal(s.view.webContents.windowOpen().action,'deny');f.win.getContentSize=()=>[230,310];f.win.emit('resize');assert(s.view.bounds.x+s.view.bounds.width<=230);assert(s.view.bounds.y+s.view.bounds.height<=310);s.controller.abort();await assert.rejects(s.promise);});
  await test('同窗口只开一项确认，不会覆盖先前等待',async()=>{const f=fixture(),s=await f.start();await assert.rejects(f.ui.confirm(f.data,new AbortController().signal),e=>e.code==='AI_APPROVAL_BUSY');s.controller.abort();await assert.rejects(s.promise);});
  console.log('独立AI确认：'+passed+' 通过 / 0 失败');
})().catch(e=>{console.error(e.stack);process.exitCode=1;});
