const fs=require('fs'),path=require('path'),os=require('os'),assert=require('assert/strict');
const {createStore}=require('../ai-permission-store');let passed=0;const roots=[];
const test=async(name,fn)=>{await fn();passed++;console.log('  ok '+name);};
function fixture(options){const root=fs.mkdtempSync(path.join(os.tmpdir(),'myide-ai-policy-'));roots.push(root);const file=path.join(root,'policy.json'),context={rootId:root,sessionId:'session'};return {root,file,context,store:createStore(file,options)};}
(async()=>{
  await test('首次迁移已有档位/白名单/项目命令，重载保留，不改旧来源',()=>{const f=fixture(),legacy={config:{permWrite:'auto',permRun:'deny',allowPaths:['docs/**']},projects:[{root:f.root,permissions:{write:true,cmds:['node']}}]},before=JSON.stringify(legacy);f.store.initialize(legacy);const p=f.store.read(1,f.context);assert.equal(p.write,'auto');assert.equal(p.run,'deny');assert(p.rememberedWrite);assert.deepEqual(p.commands,['node']);assert.equal(JSON.stringify(legacy),before);const reloaded=createStore(f.file);assert(reloaded.initialized());reloaded.initialize({config:{permWrite:'deny'}});assert.equal(reloaded.read(1,f.context).write,'auto');});
  await test('损坏/非法UTF8/未知格式不退默认值，不覆盖原件',()=>{for(const body of [Buffer.from('{broken'),Buffer.from([0xff]),Buffer.from(JSON.stringify({schema:5})),Buffer.alloc(2*1024*1024+1)]){const f=fixture();fs.writeFileSync(f.file,body);assert.throws(()=>f.store.initialize({}));assert.deepEqual(fs.readFileSync(f.file),body);assert.throws(()=>f.store.read(1,f.context));}});
  await test('权限发布失败保留旧内存、旧档位和旧磁盘，不能虚报保存',()=>{const f=fixture();f.store.initialize({});const original=fs.readFileSync(f.file);const broken=createStore(f.file,{writer:()=>{throw Object.assign(Error('fixture'),{code:'EIO'});}});broken.initialize({});assert.throws(()=>broken.updateConfig({permWrite:'auto',permRun:'auto',allowPaths:[],denyCmds:[]},0),e=>e.code==='EIO');assert.equal(broken.read(1,f.context).write,'confirm');assert.deepEqual(fs.readFileSync(f.file),original);});
  await test('外部或另一实例改权限后，旧保存和旧内存权限都拒绝，不覆盖新内容',()=>{const f=fixture();f.store.initialize({});const other=createStore(f.file);other.initialize({});other.updateConfig({permWrite:'deny',permRun:'deny',allowPaths:[],denyCmds:[]},0);const bytes=fs.readFileSync(f.file);assert.throws(()=>f.store.updateConfig({permWrite:'auto',permRun:'auto',allowPaths:[],denyCmds:[]},0),e=>e.code==='VERSION_CONFLICT');assert.deepEqual(fs.readFileSync(f.file),bytes);assert.throws(()=>f.store.read(1,f.context),e=>e.code==='VERSION_CONFLICT');});
  await test('具体选择绑定代次，撤权和恢复档位每次递增',()=>{const f=fixture();f.store.initialize({});for(const mode of ['deny','confirm']){const r=f.store.view(f.root).revision;f.store.updateConfig({permWrite:mode,permRun:'confirm',allowPaths:[],denyCmds:[]},r);assert.equal(f.store.view(f.root).revision,r+1);}assert.throws(()=>f.store.updateConfig({permWrite:'auto'},0),e=>e.code==='AI_POLICY_CHANGED');});
  await test('项目记忆隔离，清除只减权限，不误改其他命令或项目',()=>{const f=fixture();f.store.initialize({projects:[{root:f.root,permissions:{write:true,run:true,cmds:['node','npm']}},{root:path.dirname(f.root),permissions:{write:true}}]});f.store.forget(f.root,'cmd:node');f.store.forget(f.root,'write');const p=f.store.read(1,f.context);assert(!p.rememberedWrite);assert(p.rememberedRun);assert.deepEqual(p.commands,['npm']);assert(f.store.read(1,{...f.context,rootId:path.dirname(f.root)}).rememberedWrite);});
  await test('可信项目记忆绑定请求，取消或发布前失效不保存',()=>{const f=fixture();f.store.initialize({});const c=new AbortController(),data={context:f.context,call:{name:'write_file'},scope:'project'},before=fs.readFileSync(f.file);c.abort();assert.throws(()=>f.store.remember(1,data,c.signal,()=>{}),e=>e.code==='CANCELLED_AI_REQUEST');assert.deepEqual(fs.readFileSync(f.file),before);const live=new AbortController();assert.throws(()=>f.store.remember(1,data,live.signal,()=>{throw Error('old request');}));assert.deepEqual(fs.readFileSync(f.file),before);f.store.remember(1,data,live.signal,()=>{});assert(f.store.read(1,f.context).rememberedWrite);});
  await test('会话记忆只属于宿主/项目/会话，清会话后不从磁盘复活',()=>{const f=fixture();f.store.initialize({});f.store.remember(1,{context:f.context,call:{name:'run_command'},scope:'session'},new AbortController().signal,()=>{});assert(f.store.read(1,f.context).sessionRun);assert(!f.store.read(2,f.context).sessionRun);assert(!f.store.read(1,{...f.context,sessionId:'other'}).sessionRun);f.store.clearSession(1);assert(!f.store.read(1,f.context).sessionRun);assert(!createStore(f.file).read(1,f.context).sessionRun);});
  await test('命令记忆由完整已批准调用派生，不接受另外的前缀字段',()=>{const f=fixture();f.store.initialize({});f.store.remember(1,{context:f.context,call:{name:'run_command',args:{command:'node --version'}},scope:'command',prefix:'evil'},new AbortController().signal,()=>{});assert.deepEqual(f.store.read(1,f.context).commands,['node']);});
  await test('可信整会话放行有独立代次，宿主/项目/新会话隔离且不写磁盘',()=>{const f=fixture();f.store.initialize({config:{permWrite:'deny'}});const bytes=fs.readFileSync(f.file),before=f.store.view(f.root).revision;f.store.grantSession(1,f.context);const p=f.store.read(1,f.context);assert(p.sessionWrite&&p.sessionRun);assert.equal(p.write,'deny');assert.equal(f.store.view(f.root).revision,before+1);assert(!f.store.read(2,f.context).sessionWrite);assert(!f.store.read(1,{...f.context,sessionId:'new'}).sessionWrite);assert.deepEqual(fs.readFileSync(f.file),bytes);f.store.clearSession(1);assert(!f.store.read(1,f.context).sessionWrite);});
  await test('初次迁移无效路径/字段/超过项目上限，拒绝而不创建默认权限',()=>{for(const legacy of [{config:{permWrite:'invalid'}},{projects:[{root:'relative',permissions:{}}]},{projects:Array(2049).fill({root:'x'})}]){const f=fixture();assert.throws(()=>f.store.initialize(legacy));assert(!fs.existsSync(f.file));}});
  console.log('AI权限存储：'+passed+' 通过 / 0 失败');
})().catch(e=>{console.error(e.stack);process.exitCode=1;}).finally(()=>{for(const root of roots){for(const name of fs.readdirSync(root))fs.unlinkSync(path.join(root,name));fs.rmdirSync(root);}});
