const fs=require('fs'),path=require('path'),os=require('os'),cp=require('child_process'),assert=require('assert/strict'),crypto=require('crypto');
const G=require('../git-service'),Native=require('../git-native'),Status=require('../git-status'),Index=require('../git-index');
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'myide-status125-test-')),saved={};
for(const key of ['GIT_CONFIG_GLOBAL','GIT_CONFIG_NOSYSTEM','XDG_CONFIG_HOME','GIT_OPTIONAL_LOCKS','GIT_TERMINAL_PROMPT'])saved[key]=process.env[key];
Object.assign(process.env,{GIT_CONFIG_GLOBAL:path.join(temp,'global'),GIT_CONFIG_NOSYSTEM:'1',XDG_CONFIG_HOME:path.join(temp,'xdg'),GIT_OPTIONAL_LOCKS:'0',GIT_TERMINAL_PROMPT:'0'});fs.writeFileSync(process.env.GIT_CONFIG_GLOBAL,'');
const git=(root,args)=>cp.execFileSync('git',['-C',root,...args],{encoding:'utf8',windowsHide:true});
function fixture(files={'中文 空格.txt':'AAAA\n'}){const root=fs.mkdtempSync(path.join(temp,'repo-'));git(root,['init','-q']);git(root,['config','user.name','Fixture']);git(root,['config','user.email','fixture@example.invalid']);git(root,['config','core.autocrlf','false']);for(const [p,data] of Object.entries(files)){const file=path.join(root,p);fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,data);}git(root,['add','.']);git(root,['commit','-qm','base']);return root;}
const index=root=>fs.readFileSync(path.join(root,'.git','index'));
const names=st=>st.changed.map(c=>c.file.split(path.sep).join('/')).sort();
const clean=r=>assert.equal(r.completeness,'complete',JSON.stringify(r.errors));
let passed=0;async function check(name,fn){await fn();passed++;console.log('  ok '+name);}
(async()=>{try{
 await check('G1/C1：-text真实CRLF变化显示，autocrlf规范clean，两路不改原index',async()=>{for(const text of [true,false]){const root=fixture({'a.txt':'AAAA\n','.gitattributes':text?'*.txt text\n':'*.txt -text\n'});git(root,['config','core.autocrlf','true']);fs.writeFileSync(path.join(root,'a.txt'),'AAAA\r\n');const original=index(root);for(const force of [false,true]){const st=await G.status(root,{force});clean(st);assert.equal(names(st).includes('a.txt'),!text);assert.deepEqual(index(root),original);assert.equal(fs.readFileSync(path.join(root,'a.txt'),'utf8'),'AAAA\r\n');}const diff=await G.diffUnstaged(root,'a.txt');assert(!diff.error,diff.error);assert.equal(diff.unchanged,text);if(!text){assert(diff.readOnlyReason&&diff.hunks.length&&!diff.snapshot);assert(diff.hunks.flatMap(h=>h.rows).some(r=>r.bText.includes('␍')));}const js=await G.status(root,{js:true,force:true});assert(js.error&&js.errors.every(e=>e.code==='STATUS_CAPABILITY_LIMITED'));}});
 await check('G6：真实v4普通/完整扫描正确，无Git明确能力不足并保留可信列表',async()=>{const root=fixture();fs.writeFileSync(path.join(root,'中文 空格.txt'),'BBBB\n');git(root,['update-index','--index-version=4']);assert.equal(index(root).readUInt32BE(4),4);const original=index(root);for(const force of [false,true]){const st=await G.status(root,{force});clean(st);assert.deepEqual(names(st),['中文 空格.txt']);assert.deepEqual(index(root),original);}const js=await G.status(root,{js:true,force:true});assert.equal(js.completeness,'partial');assert.equal(js.errors[0].code,'INDEX_UNSUPPORTED');assert.deepEqual(names(js),['中文 空格.txt']);assert.equal(fs.readdirSync(path.join(root,'.git')).filter(n=>n.startsWith('.myide-status-')).length,0);});
 await check('G7：相同尺寸和恢复mtime，force在原生/纯JS中真实检出；原index不动',async()=>{const root=fixture({'a.txt':'AAAA\n'}),file=path.join(root,'a.txt'),stat=fs.statSync(file),original=index(root);fs.writeFileSync(file,'BBBB\n');fs.utimesSync(file,stat.atime,stat.mtime);assert.equal(fs.statSync(file).size,stat.size);assert(Math.abs(fs.statSync(file).mtimeMs-stat.mtimeMs)<1);for(const js of [false,true]){const st=await G.status(root,{js,force:true});clean(st);assert.deepEqual(names(st),['a.txt']);assert.deepEqual(index(root),original);}});
 await check('G7：完整扫描检出的同尺寸修改真的提交进HEAD，原生/无Git均保留其他暂存字节',async()=>{for(const js of [false,true]){const root=fixture({'a.txt':'AAAA\n','b.txt':'BBBB\n'}),file=path.join(root,'b.txt'),stat=fs.statSync(file);fs.writeFileSync(path.join(root,'a.txt'),'STAGED\n');git(root,['add','a.txt']);fs.writeFileSync(file,'CCCC\n');fs.utimesSync(file,stat.atime,stat.mtime);const info=Native.info,probe=Native.probe;if(js){Native.info=async()=>({git:{available:false}});Native.probe=async()=>({available:false});}try{const st=await G.status(root,{force:true});clean(st);assert(names(st).includes('b.txt'));const result=await G.commit(root,{message:'selected content',files:['b.txt'],author:{name:'Fixture',email:'fixture@example.invalid'}});assert(result.ok,result.error);assert.equal(git(root,['show','HEAD:b.txt']),'CCCC\n');assert.equal(git(root,['show','HEAD:a.txt']),'AAAA\n');assert.equal(git(root,['show',':a.txt']),'STAGED\n');}finally{Native.info=info;Native.probe=probe;}}});
 await check('G8：忽略规则第一次刷新生效，嵌套锚点与父目录否定符合原生',async()=>{for(const js of [false,true]){const root=fixture({'.gitignore':'hidden/\n','a.txt':'a\n','nested/.gitignore':'/skip.txt\n'});fs.mkdirSync(path.join(root,'hidden'));fs.writeFileSync(path.join(root,'hidden','first.txt'),'u');fs.writeFileSync(path.join(root,'nested','skip.txt'),'u');fs.writeFileSync(path.join(root,'skip.txt'),'u');clean(await G.status(root,{js}));fs.writeFileSync(path.join(root,'.gitignore'),'');const st=await G.status(root,{js,force:true});clean(st);assert(names(st).includes('hidden/first.txt'));assert(names(st).includes('skip.txt'));assert(!names(st).includes('nested/skip.txt'));fs.writeFileSync(path.join(root,'.gitignore'),'hidden/\n!hidden/first.txt\n');assert(!names(await G.status(root,{js,force:true})).includes('hidden/first.txt'));}});
 await check('G9：目录读取故障重试两次，保留旧列表而非虚构删除，恢复后正常',async()=>{const root=fixture({'sub/a.txt':'a\n'});fs.writeFileSync(path.join(root,'sub','a.txt'),'changed\n');const good=await G.status(root,{js:true,force:true});clean(good);const original=fs.readdirSync;let calls=0;fs.readdirSync=(dir,...args)=>{if(path.resolve(dir)===path.join(root,'sub')){calls++;throw Object.assign(Error('fixture EACCES'),{code:'EACCES'});}return original(dir,...args);};try{const st=await G.status(root,{js:true,force:true});assert.equal(calls,2);assert.equal(st.completeness,'partial');assert.deepEqual(st.changed,good.changed);assert.deepEqual(st.tracked,good.tracked);assert.equal(st.staleSnapshotId,good.snapshotId);}finally{fs.readdirSync=original;}clean(await G.status(root,{js:true,force:true}));});
 for(const type of ['failure','warning','truncate','invalid-utf8','limit'])await check('原生命令'+type+'不接受为空clean，保留缓存与索引，恢复可用',async()=>{const root=fixture({'a.txt':'a\n'});fs.writeFileSync(path.join(root,'a.txt'),'changed\n');const good=await G.status(root),original=index(root),run=Native.run;clean(good);let calls=0;Native.run=async(args,opts)=>{if(opts.cwd===root&&args.includes('--porcelain=v2')){calls++;if(type==='failure'||type==='limit')return {ok:false,error:type==='limit'?'stdout maxBuffer length exceeded':'fixture failure',stderr:'',stdout:''};const r=await run(args,opts);if(type==='warning')r.stderr='warning: incomplete enumeration';if(type==='truncate')r.stdout=r.stdout.subarray(0,-1);if(type==='invalid-utf8')r.stdout=Buffer.from([0xff,0]);return r;}return run(args,opts);};try{const st=await G.status(root,{force:true});assert.equal(calls,2);assert.equal(st.completeness,'partial');assert.deepEqual(st.changed,good.changed);assert.deepEqual(index(root),original);}finally{Native.run=run;}clean(await G.status(root));});
 await check('首次读取失败不返回空changed/tracked，也不宣称不是仓库',async()=>{const root=fixture(),run=Native.run;Native.run=async(args,opts)=>opts.cwd===root&&args.includes('--porcelain=v2')?{ok:false,error:'fixture failure',stdout:'',stderr:''}:run(args,opts);try{const st=await G.status(root);assert.equal(st.completeness,'error');assert.equal(st.isRepo,true);assert(!Object.hasOwn(st,'changed')&&!Object.hasOwn(st,'tracked'));}finally{Native.run=run;}});
 await check('状态失败时整份提交与读取状态的搁置/还原写端拒绝，HEAD/index/正文不变',async()=>{const root=fixture({'a.txt':'a\n'}),head=git(root,['rev-parse','HEAD']).trim();fs.writeFileSync(path.join(root,'a.txt'),'changed\n');const previous=await G.status(root);clean(previous);const before=index(root),run=Native.run;Native.run=async(args,opts)=>opts.cwd===root&&args.includes('--porcelain=v2')?{ok:false,error:'fixture failure',stdout:'',stderr:''}:run(args,opts);try{for(const action of [()=>G.commit(root,{message:'must reject',files:['a.txt']}),()=>G.shelveCreate(root,{files:['a.txt']}),()=>G.revertCommit(root,head),()=>G.cherryPick(root,head)]){const r=await action();assert.equal(r.ok,false);assert(r.error.includes('状态未完成'),r.error);assert.deepEqual(index(root),before);assert.equal(git(root,['rev-parse','HEAD']).trim(),head);assert.equal(fs.readFileSync(path.join(root,'a.txt'),'utf8'),'changed\n');}}finally{Native.run=run;}});
 await check('空仓库原生/纯JS均能完整列出未跟踪文件',async()=>{const root=fs.mkdtempSync(path.join(temp,'empty-'));git(root,['init','-q']);git(root,['config','core.autocrlf','false']);fs.writeFileSync(path.join(root,'new.txt'),'new');for(const js of [false,true]){const st=await G.status(root,{js,force:true});clean(st);assert.deepEqual(names(st),['new.txt']);assert.deepEqual(st.tracked,[]);}});
 await check('真实rename保留两端，暂存删除后重建的路径合为一次暂存+未暂存',async()=>{const root=fixture({'old.txt':'a\n'});git(root,['mv','old.txt','new.txt']);let st=await G.status(root,{force:true});clean(st);assert.deepEqual(names(st),['new.txt','old.txt']);assert(st.changed.find(c=>c.file==='old.txt').inIndexOnly);fs.writeFileSync(path.join(root,'old.txt'),'recreated');st=await G.status(root,{force:true});clean(st);assert.equal(st.changed.filter(c=>c.file==='old.txt').length,1);assert.equal(st.changed.find(c=>c.file==='old.txt').inIndexOnly,false);});
 await check('NUL记录保留中文/空格/换行/tab路径，改名与冲突；截断/坏元数据拒绝',async()=>{const oid='a'.repeat(40),file='目录/中文 空格\n\t.txt';const text=`# branch.oid ${oid}\0# branch.head dev\x001 .M N... 100644 100644 100644 ${oid} ${oid} ${file}\x002 R. N... 100644 100644 100644 ${oid} ${oid} R100 new.txt\0old.txt\0u UU N... 100644 100644 100644 100644 ${oid} ${oid} ${oid} conflict.txt\0`;const st=Status.parsePorcelain(Buffer.from(text));assert.equal(st.branch,'dev');assert.equal(st.headOid,oid);assert(st.changed.some(c=>c.file.split(path.sep).join('/')===file));assert.equal(st.changed.find(c=>c.file==='conflict.txt').status,'conflict');for(const bad of [text.slice(0,-1),text.replace('100644','broken'),text.replace('R100','Z100'),'? ../escape\0',Buffer.from([0xff,0])])assert.throws(()=>Status.parsePorcelain(bad));});
 await check('索引校验/必要扩展/截断拒绝，不把损坏索引当空树',async()=>{const root=fixture(),b=index(root);assert.equal(Index.parseIndex(b).length,1);const bad=Buffer.from(b);bad[20]^=1;assert.throws(()=>Index.parseIndex(bad));assert.throws(()=>Index.parseIndex(b.subarray(0,-20)));});
 await check('真实合并冲突原生完整扫描保留冲突与多stage，纯JS明确受限',async()=>{const root=fixture({'a.txt':'BASE\n'});git(root,['checkout','-qb','other']);fs.writeFileSync(path.join(root,'a.txt'),'OTHER\n');git(root,['commit','-qam','other']);git(root,['checkout','-q','-']);fs.writeFileSync(path.join(root,'a.txt'),'CURRENT\n');git(root,['commit','-qam','current']);assert.throws(()=>git(root,['merge','other']));const original=index(root),st=await G.status(root,{force:true});clean(st);assert.equal(st.changed.find(c=>c.file==='a.txt').status,'conflict');assert(st.tracked.includes('a.txt'));assert.deepEqual(index(root),original);const js=await G.status(root,{js:true,force:true});assert.equal(js.completeness,'partial');assert.equal(js.errors[0].code,'INDEX_UNSUPPORTED');});
 await check('split index副本展开可扫描，公开index和sharedindex全部不变',async()=>{const root=fixture({'a.txt':'a\n'});git(root,['update-index','--split-index']);fs.writeFileSync(path.join(root,'a.txt'),'changed\n');const dir=path.join(root,'.git'),owned=fs.readdirSync(dir).filter(n=>n==='index'||n.startsWith('sharedindex.')),before=new Map(owned.map(n=>[n,fs.readFileSync(path.join(dir,n))]));for(const force of [false,true]){const st=await G.status(root,{force});clean(st);assert(names(st).includes('a.txt'));for(const [n,bytes] of before)assert.deepEqual(fs.readFileSync(path.join(dir,n)),bytes);}assert.deepEqual(fs.readdirSync(dir).filter(n=>n==='index'||n.startsWith('sharedindex.')).sort(),owned.sort());});
 await check('无Git简单删除状态区分已暂存/未暂存；特殊配置不能假clean',async()=>{const root=fixture({'a.txt':'a\n','b.txt':'b\n'});fs.unlinkSync(path.join(root,'a.txt'));git(root,['rm','-q','b.txt']);const st=await G.status(root,{js:true,force:true});clean(st);assert.equal(st.changed.find(c=>c.file==='a.txt').status,'deleted');assert.equal(st.changed.find(c=>c.file==='b.txt').inIndexOnly,true);git(root,['config','include.path','../extra']);const limited=await G.status(root,{js:true,force:true});assert.equal(limited.completeness,'partial');assert.equal(limited.errors[0].code,'STATUS_CAPABILITY_LIMITED');});
 await check('完整扫描遵守外部index.lock且保留assume标志原字节；稀疏刷新明示限制',async()=>{const root=fixture({'a.txt':'a\n'}),file=path.join(root,'a.txt');git(root,['update-index','--assume-unchanged','a.txt']);fs.writeFileSync(file,'b\n');const original=index(root),lock=path.join(root,'.git','index.lock');fs.writeFileSync(lock,'external');const st=await G.status(root,{force:true});clean(st);assert(names(st).includes('a.txt'));assert.deepEqual(index(root),original);assert.equal(fs.readFileSync(lock,'utf8'),'external');fs.unlinkSync(lock);git(root,['update-index','--no-assume-unchanged','a.txt']);git(root,['update-index','--skip-worktree','a.txt']);const sparse=await G.status(root,{force:true});assert.equal(sparse.completeness,'partial');assert.equal(sparse.errors[0].code,'INDEX_UNSUPPORTED');clean(await G.status(root));});
 await check('原生未跟踪嵌套仓库目录记录有效，普通/完整均保留其他修改且不动原index',async()=>{const root=fixture({'a.txt':'BASE\n'}),nested=path.join(root,'中文 子仓库');fs.mkdirSync(nested);git(nested,['init','-q']);fs.writeFileSync(path.join(nested,'inner.txt'),'nested\n');fs.writeFileSync(path.join(root,'a.txt'),'CHANGED\n');const original=index(root);for(const force of [false,true]){const st=await G.status(root,{force});clean(st);assert.deepEqual(names(st),['a.txt','中文 子仓库']);assert.equal(st.changed.find(c=>c.file==='中文 子仓库').isDirectory,true);assert.deepEqual(index(root),original);assert.equal(fs.readFileSync(path.join(nested,'inner.txt'),'utf8'),'nested\n');}assert.throws(()=>Status.parsePorcelain('? ../escape/\0'));assert.throws(()=>Status.parsePorcelain('? child//\0'));});
 console.log(`结果: ${passed} 通过, 0 失败`);
}finally{for(const [key,value] of Object.entries(saved))if(value===undefined)delete process.env[key];else process.env[key]=value;const resolved=path.resolve(temp);if(!resolved.startsWith(path.resolve(os.tmpdir())+path.sep)||!path.basename(resolved).startsWith('myide-status125-test-'))throw Error('Unsafe fixture cleanup');fs.rmSync(resolved,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exitCode=1;});
