const fs=require('fs'),path=require('path'),os=require('os'),cp=require('child_process'),assert=require('assert/strict'),crypto=require('crypto');
const G=require('../git-service'),NativeGit=require('../git-native'),{createService}=require('../copy-journal');
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'myide-git123-test-')),savedEnv={};for(const k of ['GIT_CONFIG_GLOBAL','GIT_CONFIG_NOSYSTEM','GIT_OPTIONAL_LOCKS','GIT_TERMINAL_PROMPT'])savedEnv[k]=process.env[k];
process.env.GIT_CONFIG_GLOBAL=path.join(temp,'global');process.env.GIT_CONFIG_NOSYSTEM='1';process.env.GIT_OPTIONAL_LOCKS='0';process.env.GIT_TERMINAL_PROMPT='0';fs.writeFileSync(process.env.GIT_CONFIG_GLOBAL,'');let passed=0;
const git=(root,args,input)=>cp.execFileSync('git',['-C',root,...args],{encoding:'utf8',windowsHide:true,input});
const pick=(d,i=0,id=crypto.randomUUID())=>({snapshotId:d.snapshot.snapshotId,hunkId:d.hunks[i].hunkId,operationId:id});
function fixture(){const root=fs.mkdtempSync(path.join(temp,'repo-')),file=path.join(root,'中文 空格.txt'),rel=path.basename(file),base=Array.from({length:20},(_,i)=>'LINE'+String(i+1).padStart(2,'0'));git(root,['init','-q']);git(root,['config','user.name','Fixture']);git(root,['config','user.email','fixture@example.invalid']);git(root,['config','core.autocrlf','false']);fs.writeFileSync(file,base.join('\n')+'\n');git(root,['add','.']);git(root,['commit','-qm','base']);const shown=[...base];shown[17]='DISPLAYED-LAST';fs.writeFileSync(file,shown.join('\n')+'\n');return {root,file,rel,base,shown};}
const rawIndex=f=>fs.readFileSync(path.join(f.root,'.git','index')),data=f=>fs.readFileSync(f.file);
async function check(name,fn){await fn();passed++;console.log('  ok '+name);}
(async()=>{try{
 for(const method of ['stageHunk','revertHunk'])await check('G11 '+method+'旧视图新增前块拒绝且工作区/index字节不变',async()=>{const f=fixture(),d=await G.diffUnstaged(f.root,f.rel);f.shown[1]='UNSEEN-FIRST';fs.writeFileSync(f.file,f.shown.join('\n')+'\n');const before=data(f),index=rawIndex(f),r=await G[method](f.root,f.rel,pick(d));assert.equal(r.errorCode,'STALE_DIFF');assert.deepEqual(data(f),before);assert.deepEqual(rawIndex(f),index);});
 await check('刷新后只暂存所选第18行，其他修改留工作区，真实提交HEAD正确',async()=>{const f=fixture();f.shown[1]='UNSELECTED-FIRST';fs.writeFileSync(f.file,f.shown.join('\n')+'\n');const d=await G.diffUnstaged(f.root,f.rel),before=data(f);assert.equal(d.hunks.length,2);assert((await G.stageHunk(f.root,f.rel,pick(d,1))).ok);const index=git(f.root,['show',':'+f.rel]);assert(index.includes('DISPLAYED-LAST')&&!index.includes('UNSELECTED-FIRST'));assert.deepEqual(data(f),before);git(f.root,['commit','-qm','only-selected']);const head=git(f.root,['show','HEAD:'+f.rel]);assert.equal(head,index);assert(data(f).toString().includes('UNSELECTED-FIRST'));});
 await check('相同operationId并发/重发只执行一次，不同块复用ID拒绝',async()=>{const f=fixture(),d=await G.diffUnstaged(f.root,f.rel),selection=pick(d),[a,b]=await Promise.all([G.stageHunk(f.root,f.rel,selection),G.stageHunk(f.root,f.rel,selection)]);assert(a.ok&&b.ok&&a.oid===b.oid);const index=rawIndex(f);assert((await G.stageHunk(f.root,f.rel,selection)).ok);assert.deepEqual(rawIndex(f),index);assert.equal((await G.stageHunk(f.root,f.rel,{...selection,hunkId:'changed'})).errorCode,'OPERATION_CONFLICT');assert.equal((await G.stageHunk(f.root,f.rel,pick(d))).errorCode,'STALE_DIFF');});
 for(const change of ['shown','add','head','attributes','config','move','delete','same-size-time'])await check('快照后'+change+'变化拒绝，保留外部工作区与完整index',async()=>{const f=fixture(),d=await G.diffUnstaged(f.root,f.rel);if(change==='shown')fs.writeFileSync(f.file,data(f).toString().replace('DISPLAYED-LAST','DIFFERENT-LAST'));if(change==='add')git(f.root,['add',f.rel]);if(change==='head')git(f.root,['commit','--allow-empty','-qm','external-head']);if(change==='attributes')fs.writeFileSync(path.join(f.root,'.gitattributes'),'*.txt -text\n');if(change==='config')git(f.root,['config','core.autocrlf','true']);if(change==='move')fs.renameSync(f.file,f.file+'.moved');if(change==='delete')fs.unlinkSync(f.file);if(change==='same-size-time'){const stat=fs.statSync(f.file);fs.writeFileSync(f.file,data(f).toString().replace('DISPLAYED-LAST','UNSEEN-CHANGE!'));fs.utimesSync(f.file,stat.atime,stat.mtime);assert.equal(fs.statSync(f.file).size,stat.size);assert(Math.abs(fs.statSync(f.file).mtimeMs-stat.mtimeMs)<1);}const before=fs.existsSync(f.file)?data(f):null,index=rawIndex(f);assert.equal((await G.stageHunk(f.root,f.rel,pick(d))).errorCode,'STALE_DIFF');assert.deepEqual(fs.existsSync(f.file)?data(f):null,before);assert.deepEqual(rawIndex(f),index);});
 await check('已暂存视图后外部add拒绝取消暂存，不损失外部index',async()=>{const f=fixture();git(f.root,['add',f.rel]);const d=await G.diffStaged(f.root,f.rel);f.shown[1]='EXTERNAL-STAGED';fs.writeFileSync(f.file,f.shown.join('\n')+'\n');git(f.root,['add',f.rel]);const before=rawIndex(f),work=data(f);assert.equal((await G.unstageHunk(f.root,f.rel,pick(d))).errorCode,'STALE_DIFF');assert.deepEqual(rawIndex(f),before);assert.deepEqual(data(f),work);});
 await check('正常取消暂存仅移除选中第18行，不改变工作区与其他文件',async()=>{const f=fixture();f.shown[1]='FIRST-STAGED';fs.writeFileSync(f.file,f.shown.join('\n')+'\n');const other=path.join(f.root,'other.txt');fs.writeFileSync(other,'other staged');git(f.root,['add','.']);const d=await G.diffStaged(f.root,f.rel),before=data(f),otherOid=git(f.root,['rev-parse',':other.txt']);assert((await G.unstageHunk(f.root,f.rel,pick(d,1))).ok);const index=git(f.root,['show',':'+f.rel]);assert(index.includes('FIRST-STAGED')&&!index.includes('DISPLAYED-LAST'));assert.deepEqual(data(f),before);assert.equal(git(f.root,['rev-parse',':other.txt']),otherOid);});
 await check('index.lock已占用明确拒绝，保留外部锁与index',async()=>{const f=fixture(),d=await G.diffUnstaged(f.root,f.rel),lock=path.join(f.root,'.git','index.lock');fs.writeFileSync(lock,'external lock');const before=rawIndex(f);assert.equal((await G.stageHunk(f.root,f.rel,pick(d))).errorCode,'INDEX_LOCKED');assert.equal(fs.readFileSync(lock,'utf8'),'external lock');assert.deepEqual(rawIndex(f),before);});
 await check('index独立副本写入故障不修改公开index，不残留自己的锁',async()=>{const f=fixture(),d=await G.diffUnstaged(f.root,f.rel),before=rawIndex(f),write=fs.promises.writeFile;fs.promises.writeFile=async(p,...args)=>{if(String(p).endsWith('index.lock'))throw Object.assign(Error('fixture index ENOSPC'),{code:'ENOSPC'});return write.call(fs.promises,p,...args);};try{assert(!(await G.stageHunk(f.root,f.rel,pick(d))).ok);}finally{fs.promises.writeFile=write;}assert.deepEqual(rawIndex(f),before);assert(!fs.existsSync(path.join(f.root,'.git','index.lock')));});
 await check('index写入及锁清理同时失败返回残留路径，不假报成功',async()=>{const f=fixture(),d=await G.diffUnstaged(f.root,f.rel),before=rawIndex(f),lock=path.join(f.root,'.git','index.lock'),write=fs.promises.writeFile,unlink=fs.unlinkSync;fs.promises.writeFile=async(p,...args)=>{if(String(p)===lock)throw Object.assign(Error('fixture ENOSPC'),{code:'ENOSPC'});return write.call(fs.promises,p,...args);};fs.unlinkSync=p=>{if(String(p)===lock)throw Object.assign(Error('fixture cleanup denied'),{code:'EACCES'});return unlink(p);};let result;try{result=await G.stageHunk(f.root,f.rel,pick(d));}finally{fs.promises.writeFile=write;fs.unlinkSync=unlink;}assert.equal(result.errorCode,'INDEX_CLEANUP_FAILED');assert.equal(result.pendingIndexLock,lock);assert(!result.ok&&fs.existsSync(lock));assert.deepEqual(rawIndex(f),before);fs.unlinkSync(lock);});
 await check('原序号/伪造块/另一项目/越界路径不能获得写入授权',async()=>{const f=fixture(),other=fixture(),d=await G.diffUnstaged(f.root,f.rel),before=rawIndex(f);assert.equal((await G.stageHunk(f.root,f.rel,0)).errorCode,'SNAPSHOT_REQUIRED');assert.equal((await G.stageHunk(f.root,f.rel,{...pick(d),hunkId:'foreign'})).errorCode,'STALE_DIFF');assert.equal((await G.stageHunk(other.root,other.rel,pick(d))).errorCode,'STALE_DIFF');assert.equal((await G.diffUnstaged(f.root,'../outside')).errorCode,'OUTSIDE_REPO');assert.equal((await G.diffUnstaged(f.root,'..')).errorCode,'OUTSIDE_REPO');assert.equal((await G.diffUnstaged(f.root,'.GIT/config')).errorCode,'OUTSIDE_REPO');assert.deepEqual(rawIndex(f),before);});
 await check('读取中途改动拒绝发放混合版本快照',async()=>{const f=fixture(),run=NativeGit.run;let changed=false;NativeGit.run=async(...args)=>{if(!changed&&args[0][0]==='check-attr'){changed=true;fs.writeFileSync(f.file,'changed during read');}return run(...args);};try{assert.equal((await G.diffUnstaged(f.root,f.rel)).errorCode,'STALE_DIFF');}finally{NativeGit.run=run;}});
 await check('回退只改变选中块，原字节/ADS可从持久记录恢复',async()=>{const f=fixture();f.shown[1]='KEEP-FIRST';fs.writeFileSync(f.file,f.shown.join('\n')+'\n');fs.writeFileSync(f.file+':private','original ADS');const before=data(f),index=rawIndex(f),d=await G.diffUnstaged(f.root,f.rel),cache=path.join(temp,'recover-'+crypto.randomUUID()),r=await G.revertHunk(f.root,f.rel,pick(d,1),cache);assert(r.ok&&r.recoveryOperationId);const work=data(f).toString();assert(work.includes('KEEP-FIRST')&&!work.includes('DISPLAYED-LAST'));assert.equal(fs.readFileSync(f.file+':private','utf8'),'original ADS');assert.deepEqual(rawIndex(f),index);assert(createService(cache).undo(f.root,r.recoveryOperationId).ok);assert.deepEqual(data(f),before);assert.equal(fs.readFileSync(f.file+':private','utf8'),'original ADS');});
 await check('ADS后来变化拒绝回退，不覆盖新流或正文',async()=>{const f=fixture();fs.writeFileSync(f.file+':private','old stream');const d=await G.diffUnstaged(f.root,f.rel);fs.writeFileSync(f.file+':private','new stream');const before=data(f),index=rawIndex(f);assert.equal((await G.revertHunk(f.root,f.rel,pick(d))).errorCode,'STALE_DIFF');assert.deepEqual(data(f),before);assert.equal(fs.readFileSync(f.file+':private','utf8'),'new stream');assert.deepEqual(rawIndex(f),index);});
 await check('全局attributes版本变化使旧展示失效',async()=>{const f=fixture(),attrs=path.join(temp,'global-attrs');fs.writeFileSync(attrs,'*.txt -text\n');git(f.root,['config','core.attributesFile',attrs]);const d=await G.diffUnstaged(f.root,f.rel);fs.writeFileSync(attrs,'*.txt text\n');const before=rawIndex(f);assert.equal((await G.stageHunk(f.root,f.rel,pick(d))).errorCode,'STALE_DIFF');assert.deepEqual(rawIndex(f),before);});
 await check('index原生发布失败仍保留公开index与工作区，清自己锁',async()=>{const f=fixture(),d=await G.diffUnstaged(f.root,f.rel),before=rawIndex(f),work=data(f),N=require('../file-copy-win'),publish=N.publish;N.publish=(tmp,target,...rest)=>{if(target.endsWith(path.sep+'index'))throw Object.assign(Error('fixture publish denied'),{code:'EACCES'});return publish(tmp,target,...rest);};try{assert.equal((await G.stageHunk(f.root,f.rel,pick(d))).errorCode,'EACCES');}finally{N.publish=publish;}assert.deepEqual(rawIndex(f),before);assert.deepEqual(data(f),work);assert(!fs.existsSync(path.join(f.root,'.git','index.lock')));});
 await check('持锁后核对期间外部正文变化拒绝发布',async()=>{const f=fixture(),d=await G.diffUnstaged(f.root,f.rel),before=rawIndex(f),run=NativeGit.run;let reads=0;NativeGit.run=async(...args)=>{if(args[0][0]==='check-attr'&&++reads===2)fs.writeFileSync(f.file,'late external content');return run(...args);};try{assert.equal((await G.stageHunk(f.root,f.rel,pick(d))).errorCode,'STALE_DIFF');}finally{NativeGit.run=run;}assert.deepEqual(rawIndex(f),before);assert.equal(fs.readFileSync(f.file,'utf8'),'late external content');assert(!fs.existsSync(path.join(f.root,'.git','index.lock')));});
 await check('CRLF正向对照保持LF index与原工作区字节',async()=>{const f=fixture();git(f.root,['config','core.autocrlf','true']);fs.writeFileSync(f.file,f.shown.join('\r\n')+'\r\n');const before=data(f),d=await G.diffUnstaged(f.root,f.rel);assert((await G.stageHunk(f.root,f.rel,pick(d))).ok);assert(!git(f.root,['show',':'+f.rel]).includes('\r'));assert.deepEqual(data(f),before);});
 console.log('结果: '+passed+' 通过, 0 失败');
}finally{for(const [k,v] of Object.entries(savedEnv)){if(v===undefined)delete process.env[k];else process.env[k]=v;}if(path.dirname(temp)!==path.resolve(os.tmpdir())||!path.basename(temp).startsWith('myide-git123-test-'))throw Error('Unsafe cleanup');fs.rmSync(temp,{recursive:true,force:true});}})().catch(e=>{console.error(e.stack||e);process.exitCode=1;});
