const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{JSDOM}=require('jsdom');const root=path.join(__dirname,'..');let passed=0;const all=[];
const tick=()=>new Promise(r=>setTimeout(r,20));
async function fixture(){const dom=new JSDOM(fs.readFileSync(path.join(root,'renderer/index.html'),'utf8'),{runScripts:'outside-only',pretendToBeVisual:true});all.push(dom);const w=dom.window,q=id=>w.document.getElementById(id),toasts=[],calls=[],timers=[];
  let cfg={entries:[{id:'a',name:'终端A',command:'echo A',port:3000}],apiOrigins:[],keepOnExit:false};let status={id:'a',alive:true,processAlive:true,ownership:'owned',canStop:true,canStart:false,phase:'running',by:'proc'};
  w.setInterval=fn=>{timers.push(fn);return 1;};w.clearInterval=()=>{};w.MI={toast:msg=>toasts.push(msg)};
  const api={config:async()=>cfg,status:async()=>[status],logs:async()=>({lines:['日志保留'],records:[{seq:1,text:'日志保留'}],generation:'a',runId:'r',version:1}),getKeep:async()=>false,save:async value=>{calls.push(['save',value]);cfg=value;return value;},start:async()=>{calls.push(['start']);return{ok:true};},stop:async()=>{calls.push(['stop']);return{ok:true};},openUrl:async url=>{calls.push(['open',url]);}};
  w.myIDE={launch:api};q('launch-main').classList.remove('hidden');w.eval(fs.readFileSync(path.join(root,'renderer/launch-panel.js'),'utf8'));w.LaunchPanel.init();await tick();q('launch-body').querySelector('[data-id=a]').click();await tick();
  return{w,q,api,toasts,calls,entry:()=>cfg.entries[0],status:value=>{status={...status,...value};},poll:async()=>{await timers[0]();await tick();},edit:()=>q('lm-edit').click(),mode:value=>{q('launch-ready-mode').value=value;q('launch-ready-mode').dispatchEvent(new w.Event('change'));},save:async()=>{q('launch-dialog-ok').click();await tick();}};
}
const test=async(name,fn)=>{await fn();passed++;console.log('ok '+name);};
(async()=>{try{
  await test('等待/输出就绪/端口来源/超时/不可用/未知均可回看，不自动打开或停止',async()=>{
    const f=await fixture();const before=f.q('lm-log').textContent;
    for(const [state,mode,text]of [['waiting','output','等待就绪'],['ready','output','本次输出已匹配'],['ready','port','来源未验证'],['timed-out','output','就绪超时'],['unavailable','port','端口不再响应'],['unknown','output','就绪未确认']]){f.status({readiness:{state,mode,timeoutSeconds:1,reason:state==='unknown'?'后台缺证据':''}});await f.poll();assert(f.q('lm-state').textContent.includes(text));assert(!f.q('lm-stop').disabled);assert.equal(f.q('lm-log').textContent,before);}
    assert.equal(f.calls.length,0);assert(f.q('lm-operation-text').textContent.includes('后台缺证据'));
  });
  await test('退出立即清除就绪展示，旧服务缺readiness仍明确未验证',async()=>{const f=await fixture();f.status({readiness:{state:'ready',mode:'output'}});await f.poll();assert.match(f.q('lm-state').textContent,/已就绪/);f.status({processAlive:false,alive:false,phase:'exited',exitCode:7});await f.poll();assert.match(f.q('lm-state').textContent,/异常退出/);assert(!f.q('lm-state').textContent.includes('已就绪'));});
  await test('编辑旧配置缺省无需验证，切换条件显示对应字段/边界，取消不保存不执行',async()=>{const f=await fixture();f.edit();assert.equal(f.q('launch-ready-mode').value,'none');assert(f.q('launch-ready-text-field').hidden);f.mode('port');assert.match(f.q('launch-ready-help').textContent,/不能证明/);assert(!f.q('launch-ready-timeout-field').hidden);f.mode('output');assert(!f.q('launch-ready-text-field').hidden);f.q('launch-dialog-cancel').click();assert.equal(f.calls.length,0);});
  await test('保存输出规则保留原文字面空格、timeout与其他字段，保存不执行命令',async()=>{const f=await fixture();f.edit();f.mode('output');f.q('launch-ready-text').value=' ready🙂 ';f.q('launch-ready-timeout').value='5';await f.save();assert.deepEqual(JSON.parse(JSON.stringify(f.entry().readiness)),{mode:'output',timeoutSeconds:5,text:' ready🙂 '});assert.equal(f.calls.length,1);assert.equal(f.calls[0][0],'save');f.edit();assert.equal(f.q('launch-ready-text').value,' ready🙂 ');});
  await test('无效输出/超时/端口/USB均拒绝保存，保留表单和原配置供修正',async()=>{const f=await fixture();f.edit();f.mode('output');await f.save();assert.equal(f.calls.length,0);f.q('launch-ready-text').value='ok';f.q('launch-ready-timeout').value='1.5';await f.save();assert.equal(f.calls.length,0);f.q('launch-ready-timeout').value='5';f.mode('port');f.q('launch-form').elements.port.value='0';await f.save();assert.equal(f.calls.length,0);f.mode('output');f.q('launch-form').elements.kind.value='usb-tunnel';await f.save();assert.equal(f.calls.length,0);assert.equal(f.entry().readiness,undefined);assert(f.q('launch-dialog').hasAttribute('open'));assert.match(f.toasts.at(-1),/daemon/);});
  await test('保存拒绝保留已填规则和旧配置，明确失败后可重试；无需验证移除旧匹配',async()=>{const f=await fixture();f.entry().readiness={mode:'output',text:'old',timeoutSeconds:30};f.edit();f.mode('none');const actual=f.api.save;f.api.save=async()=>{throw Error('落盘拒绝');};await f.save();assert.equal(f.entry().readiness.mode,'output');assert(f.q('launch-dialog').hasAttribute('open'));assert.match(f.toasts.at(-1),/落盘拒绝/);f.api.save=actual;await f.save();assert.deepEqual(JSON.parse(JSON.stringify(f.entry().readiness)),{mode:'none'});});
  console.log('就绪DOM：'+passed+' 通过 / 0 失败');
}finally{all.forEach(dom=>dom.window.close());}})().catch(error=>{console.error(error);process.exitCode=1;});
