const fs=require('fs'),path=require('path'),os=require('os'),assert=require('assert/strict');
const {createMover}=require('../path-move'),FileWrite=require('../file-write');
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'myide-path-move-test-'));let passed=0;
const check=(name,fn)=>{fn();passed++;console.log('  ok '+name);};
const fixture=()=>{const folder=fs.mkdtempSync(path.join(temp,'case-')),src=path.join(folder,'source');fs.mkdirSync(src);fs.mkdirSync(path.join(src,'sub'));fs.writeFileSync(path.join(src,'sub','a.txt'),'正文\r\n');fs.writeFileSync(path.join(src,'b.bin'),Buffer.from([0,255,1]));return {folder,src,file:path.join(src,'sub','a.txt'),dest:path.join(folder,'dest')};};
try {
  check('文件/目录真实排他移动与原字节/文档新基线',()=>{const {src,file,dest}=fixture(),m=createMover(),base=FileWrite.readSnapshot(file);const r=m.relocate(src,dest,{expectedSource:m.snapshot(src),documents:[{path:file,version:base.version}]});assert(r.ok&&r.after&&r.documents.length===1);assert(!fs.existsSync(src));assert.equal(fs.readFileSync(path.join(dest,'sub','a.txt'),'utf8'),'正文\r\n');assert(FileWrite.sameVersion(r.documents[0].version,FileWrite.readSnapshot(path.join(dest,'sub','a.txt')).version));assert.deepEqual(fs.readFileSync(path.join(dest,'b.bin')),Buffer.from([0,255,1]));});
  check('正常undo按原完整路径恢复，不另取名',()=>{const {src,dest}=fixture(),m=createMover(),r=m.relocate(src,dest);const undo=m.relocate(dest,src,{expectedSource:r.after});assert(undo.ok&&fs.existsSync(path.join(src,'sub','a.txt'))&&!fs.existsSync(dest));});
  check('同尺寸且mtime复原的后代修改使旧undo失效',()=>{const {src,dest}=fixture(),m=createMover(),r=m.relocate(src,dest),file=path.join(dest,'sub','a.txt'),st=fs.statSync(file);fs.writeFileSync(file,'修改\r\n');fs.utimesSync(file,st.atime,st.mtime);assert.throws(()=>m.relocate(dest,src,{expectedSource:r.after}),{code:'STALE_OPERATION'});assert.equal(fs.readFileSync(file,'utf8'),'修改\r\n');assert(!fs.existsSync(src));});
  check('已有目的保留两方，旧undo失败后可重试',()=>{const {src,dest}=fixture(),m=createMover(),r=m.relocate(src,dest);fs.mkdirSync(src);fs.writeFileSync(path.join(src,'external'),'keep');assert.throws(()=>m.relocate(dest,src,{expectedSource:r.after}),{code:'DEST_CONFLICT'});assert(fs.existsSync(dest));assert.equal(fs.readFileSync(path.join(src,'external'),'utf8'),'keep');fs.unlinkSync(path.join(src,'external'));fs.rmdirSync(src);assert(m.relocate(dest,src,{expectedSource:r.after}).ok);});
  check('目标存在时移动保留自动另名与已有字节',()=>{const {folder,src}=fixture(),dest=path.join(folder,'target');fs.mkdirSync(dest);fs.mkdirSync(path.join(dest,'source'));fs.writeFileSync(path.join(dest,'source','keep'),'external');const r=createMover().moveTo(src,dest);assert.equal(path.basename(r.target),'source (1)');assert.equal(fs.readFileSync(path.join(dest,'source','keep'),'utf8'),'external');});
  check('原读取文档版本被外部修改时迁移前拒绝',()=>{const {src,file,dest}=fixture(),m=createMover(),base=FileWrite.readSnapshot(file);fs.writeFileSync(file,'external');assert.throws(()=>m.relocate(src,dest,{documents:[{path:file,version:base.version}]}),{code:'VERSION_CONFLICT'});assert.equal(fs.readFileSync(file,'utf8'),'external');assert(!fs.existsSync(dest));});
  check('目的最终范围有打开文档拒绝，即使目标目前不存在',()=>{const {src,dest}=fixture();assert.throws(()=>createMover().relocate(src,dest,{openTargets:[path.join(dest,'sub','a.txt')]}),{code:'DEST_OPEN'});assert(fs.existsSync(src)&&!fs.existsSync(dest));});
  check('路径段边界不把source-other当source后代',()=>{const {folder,src}=fixture(),dest=path.join(folder,'source-other');fs.mkdirSync(dest);assert(createMover().moveTo(src,dest).ok);});
  check('目标后代拒绝不修改磁盘',()=>{const {src}=fixture();assert.throws(()=>createMover().moveTo(src,path.join(src,'sub')),{code:'INVALID_TARGET'});assert(fs.existsSync(path.join(src,'sub','a.txt')));});
  check('目录junction与链接祖先明确拒绝',()=>{const {folder,src,dest}=fixture(),alias=path.join(folder,'alias');fs.symlinkSync(src,alias,process.platform==='win32'?'junction':'dir');assert.throws(()=>createMover().relocate(alias,dest),{code:'LINK_PATH'});assert.throws(()=>createMover().relocate(path.join(alias,'sub'),dest),{code:'LINK_PATH'});assert(fs.existsSync(src));});
  check('源后代junction明确拒绝且不迁移外部目标',()=>{const {folder,src,dest}=fixture(),outside=path.join(folder,'outside');fs.mkdirSync(outside);fs.symlinkSync(outside,path.join(src,'alias'),process.platform==='win32'?'junction':'dir');assert.throws(()=>createMover().relocate(src,dest),{code:'LINK_PATH'});assert(fs.existsSync(src)&&fs.existsSync(outside)&&!fs.existsSync(dest));});
  check('名称校验不允许路径逃逸和Windows设备名',()=>{const {src}=fixture();for(const name of ['../out','x/y','x\\y','..','CON','a.','a '])assert.throws(()=>createMover().rename(src,name),{code:'INVALID_NAME'});assert(fs.existsSync(src));});
  check('真实Windows大小写改名与摘要撤销',()=>{const {src}=fixture(),m=createMover(),r=m.rename(src,'SOURCE');assert(fs.readdirSync(path.dirname(src)).includes('SOURCE'));assert(m.relocate(r.path,src,{expectedSource:r.after}).ok);assert(fs.readdirSync(path.dirname(src)).includes('source'));});
  check('排他原生调用遇后来创建目标不覆盖',()=>{const {src,dest}=fixture(),m=createMover(fs,(source,target)=>{fs.mkdirSync(target);throw Object.assign(Error('race'),{code:'EEXIST'});});assert.throws(()=>m.relocate(src,dest),{code:'DEST_CONFLICT'});assert(fs.existsSync(src)&&fs.existsSync(dest));});
  check('EXDEV错误保留源，不回落复制删除',()=>{const {src,dest}=fixture(),m=createMover(fs,()=>{throw Object.assign(Error('cross device'),{code:'EXDEV'});});assert.throws(()=>m.relocate(src,dest),{code:'EXDEV'});assert(fs.existsSync(src)&&!fs.existsSync(dest));});
  check('平台预算超限在破坏前拒绝',()=>{const {src,dest}=fixture();const io=Object.assign(Object.create(fs),{readdirSync(p){return p===src?Array.from({length:10001},()=> 'b.bin'):fs.readdirSync(p);}});assert.throws(()=>createMover(io).relocate(src,dest),{code:'MOVE_LIMIT'});assert(fs.existsSync(src)&&!fs.existsSync(dest));});
  check('摘要字节预算在打开大文件前拒绝',()=>{const {src,dest}=fixture();let opened=false;const io=Object.assign(Object.create(fs),{lstatSync(p){const s=fs.lstatSync(p);if(s.isFile())return Object.assign(Object.create(s),{size:257*1024*1024});return s;},openSync(){opened=true;throw Error('不得读取');}});assert.throws(()=>createMover(io).relocate(src,dest),{code:'MOVE_LIMIT'});assert(!opened&&fs.existsSync(src)&&!fs.existsSync(dest));});
  check('提交后核对失败返回迁移事实，不假报源仍原位',()=>{const {src,dest}=fixture(),m=createMover(fs,(source,target)=>{require('../file-replace-win').createFile(source,target);fs.writeFileSync(path.join(target,'new-link-target'),'x');fs.symlinkSync(path.join(target,'sub'),path.join(target,'alias'),'junction');});const r=m.relocate(src,dest);assert(r.ok&&r.warning&&!r.after&&!fs.existsSync(src)&&fs.existsSync(dest));});
}catch(e){console.error(e);process.exitCode=1;}
finally{if(path.dirname(path.resolve(temp))!==path.resolve(os.tmpdir())||!path.basename(temp).startsWith('myide-path-move-test-'))throw Error('Unsafe cleanup');fs.rmSync(temp,{recursive:true,force:true});}
console.log('结果: '+passed+' 通过, '+(process.exitCode?1:0)+' 失败');
