const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{JSDOM}=require('jsdom');const root=path.resolve(__dirname,'..');let passed=0;
const gate=()=>{let resolve;const promise=new Promise(r=>resolve=r);return {resolve,promise};};
async function fixture(){const dom=new JSDOM(fs.readFileSync(path.join(root,'renderer/index.html'),'utf8'),{url:'https://myide.test',runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window;await new Promise(r=>setImmediate(r));
 const files=new Map([['C:/project/a.md','# 原文\r\n\r\n原阅读位置。'],['C:/project/b.md','# needle\r\n\r\n😀 **needle** needle\r\n\r\n[显示](https://needle.example)'],['C:/project/c.md','# 第三页\n\nneedle']]);const version=p=>({schema:1,target:p,stamp:'test:'+p,hash:files.get(p)});let writes=0;
 w.localStorage.setItem('myide-md-mode','preview');w.HTMLElement.prototype.scrollIntoView=()=>{};w.HTMLCanvasElement.prototype.getContext=()=>({measureText:s=>({width:s.length*6})});
 w.App={root:'C:/project',getTool:()=>null,ftIcon:()=>'<svg></svg>',dirIcon:()=>'',updateStatusbar(){},refreshOutline(){},backToEditor(){}};w.Tree={reveal(){}};w.Modal={stack:[]};w.Session={save(){}};w.Shortcuts={bindings:()=>[],onChanged(){},invalidateContext(){}};
 const bridge={readFile:async p=>files.has(p)?{content:files.get(p),encoding:'utf8',version:version(p)}:{error:'文件不存在'},fileVersion:async p=>({version:version(p)}),onChanged(){},writeFile:async()=>{writes++;throw Error('不得写盘');}};w.myIDE={fs:bridge};
 for(const f of ['vendor/marked.min.js','text-lines.js','document-paths.js','tab-descriptions.js','closed-tabs.js','navigation-history.js','search-model.js','preview-location.js','plugin-loader.js','viewer.js'])w.eval(fs.readFileSync(path.join(root,'renderer',f),'utf8'));
 w.NavigationHistory.init({capture:()=>w.Viewer.captureLocation(),restore:(...args)=>w.Viewer.restoreLocation(...args)});w.NavigationHistory.reset(w.App.root);
 await w.Viewer.openFile('C:/project/a.md');w.NavigationHistory.reset(w.App.root);
 const hit=(p,n=0)=>{const raw=files.get(p);let start=-1;for(let i=0;i<=n;i++)start=raw.indexOf('needle',start+1);const before=raw.slice(0,start),line=before.split('\n').length,startColumn=start-before.lastIndexOf('\n');return {path:p,version:version(p),encoding:'utf8',match:'needle',startOffset:start,endOffset:start+6,line,startColumn,endColumn:startColumn+6};};
 return {w,files,bridge,hit,version,writes:()=>writes,close:()=>w.close()};}
const test=async(name,fn)=>{const f=await fixture();try{await fn(f);passed++;console.log('ok '+name);}finally{f.close();}};
(async()=>{
 await test('预览连续命中保持模式/文档身份与原CRLF/emoji，成功才记导航历史',async f=>{const {w}=f,a=w.Viewer.activeTab;const first=await w.Viewer.navigateToHit(f.hit('C:/project/b.md',1));assert(first.ok);const b=w.Viewer.activeTab;assert.equal(b.mode,'preview');assert.equal(w.Viewer.cm,null);assert.equal(b.content,f.files.get(b.path));assert.equal(w.NavigationHistory.state().back,1);assert((await w.Viewer.navigateToHit(f.hit(b.path,2))).ok);assert.equal(w.Viewer.activeTab,b);assert.equal(w.NavigationHistory.state().back,2);assert((await w.NavigationHistory.travel('back')).ok);assert.equal(w.Viewer.activeTab,b);assert((await w.NavigationHistory.travel('back')).ok);assert.equal(w.Viewer.activeTab,a);assert((await w.NavigationHistory.travel('forward')).ok);assert.equal(w.Viewer.activeTab,b);assert.equal(f.writes(),0);});
 await test('不可见URL/没有映射的插件失败前保留原页面、标签集合与历史',async f=>{const {w}=f,a=w.Viewer.activeTab,el=w.document.getElementById('viewer').firstElementChild;const failed=await w.Viewer.navigateToHit(f.hit('C:/project/b.md',3));assert.equal(failed.errorCode,'UNSUPPORTED_VIEW');assert.equal(w.Viewer.activeTab,a);assert.equal(w.Viewer.openTabs.length,1);assert.equal(w.document.getElementById('viewer').firstElementChild,el);assert.equal(w.NavigationHistory.state().back,0);});
 await test('候选读取拒绝或无版本不能切页/增标签，不把旧页面当打开成功',async f=>{const {w}=f,a=w.Viewer.activeTab;f.bridge.readFile=async()=>({error:'权限拒绝'});const result=await w.Viewer.navigateToHit(f.hit('C:/project/b.md'));assert.equal(result.errorCode,'READ_FAILED');assert.equal(w.Viewer.activeTab,a);assert.equal(w.Viewer.openTabs.length,1);assert.equal(w.NavigationHistory.state().back,0);});
 await test('候选读取期间换项目/查询取消，迟到读取不改变当前页面',async f=>{const {w}=f,a=w.Viewer.activeTab,read=f.bridge.readFile,pause=gate();f.bridge.readFile=p=>p.endsWith('b.md')?pause.promise:read(p);let current=true;const navigation=w.Viewer.navigateToHit(f.hit('C:/project/b.md'),{isCurrent:()=>current});await new Promise(r=>setImmediate(r));current=false;pause.resolve(await read('C:/project/b.md'));assert((await navigation).stale);assert.equal(w.Viewer.activeTab,a);assert.equal(w.Viewer.openTabs.length,1);});
 await test('读取期间用户已切另一个标签，旧命中不切回来',async f=>{const {w}=f,read=f.bridge.readFile,pause=gate();f.bridge.readFile=p=>p.endsWith('b.md')?pause.promise:read(p);const navigation=w.Viewer.navigateToHit(f.hit('C:/project/b.md'));await new Promise(r=>setImmediate(r));await w.Viewer.openFile('C:/project/c.md');const c=w.Viewer.activeTab;pause.resolve(await read('C:/project/b.md'));assert((await navigation).stale);assert.equal(w.Viewer.activeTab,c);assert(!w.Viewer.openTabs.some(t=>t.path.endsWith('b.md')));});
 await test('磁盘版本/dirty过期命中拒绝，原标签及位置仍保留',async f=>{const {w}=f,a=w.Viewer.activeTab,hit=f.hit('C:/project/b.md');f.files.set(hit.path,'外部 needle');assert.equal((await w.Viewer.navigateToHit(hit)).errorCode,'VERSION_CONFLICT');assert.equal(w.Viewer.activeTab,a);await w.Viewer.openFile(hit.path);w.Viewer.activeTab.dirty=true;w.Viewer.activate(0);assert.equal((await w.Viewer.navigateToHit(f.hit(hit.path))).errorCode,'DIRTY_DOCUMENT');assert.equal(w.Viewer.activeTab,a);assert.equal(f.writes(),0);});
 await test('懒恢复搜索只读取一次，激活不再次覆写命中',async f=>{const {w}=f,p='C:/project/b.md',read=f.bridge.readFile;w.Viewer.addLazyTab(p,{line:1});let reads=0;f.bridge.readFile=async path=>{if(path===p)reads++;return read(path);};assert((await w.Viewer.navigateToHit(f.hit(p,1))).ok);await new Promise(r=>setImmediate(r));assert.equal(reads,1);assert.equal(w.Viewer.activeTab.lazy,false);assert.equal(w.Viewer.captureLocation().scroll.previewAnchor.highlight.from,f.hit(p,1).startOffset);});
 await test('预览历史在本地正文插入后同步语义锚与高亮范围',async f=>{const {w}=f,p='C:/project/b.md',hit=f.hit(p,1);assert((await w.Viewer.navigateToHit(hit)).ok);const b=w.Viewer.activeTab;assert((await w.Viewer.navigateToHit(f.hit('C:/project/c.md'))).ok);b.content='前缀'+b.content;w.NavigationHistory.edited(b,offset=>offset+2);b.editRevision++;b.dirty=true;assert((await w.NavigationHistory.travel('back')).ok);assert.equal(w.Viewer.activeTab,b);assert.equal(w.Viewer.captureLocation().scroll.previewAnchor.highlight.from,hit.startOffset+2);assert.equal(f.writes(),0);});
 console.log('预览导航：'+passed+' 通过 / 0 失败');
})().catch(e=>{console.error(e);process.exitCode=1;});
