const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{JSDOM}=require('jsdom');
const root=path.resolve(__dirname,'..');let passed=0;
const dom=new JSDOM('<body><div id="toast-wrap"></div></body>',{url:'https://myide.test',runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window;
for(const f of ['vendor/marked.min.js','preview-location.js','plugin-loader.js'])w.eval(fs.readFileSync(path.join(root,'renderer',f),'utf8'));
w.HTMLElement.prototype.scrollIntoView=()=>{};
const render=raw=>{const node=w.MI.renderFor({name:'a.md'})({path:'C:/project/a.md',content:raw});w.document.body.append(node);return node;};
const hit=(node,raw,word,n=0)=>{let at=-1;for(let i=0;i<=n;i++)at=raw.indexOf(word,at+1);assert(at>=0);return w.PreviewLocation.locate(node,at,at+word.length);};
const test=(name,fn)=>{fn();passed++;console.log('ok '+name);};
try{
 test('标题/多段/同一行第二词/emoji/CRLF按源码范围映射，保留原渲染语义',()=>{const raw='# 标题 needle\r\n\r\n😀 needle **needle** *needle* ~~needle~~\r\n\r\n下一段 needle';const el=render(raw);for(let i=0;i<6;i++)assert.equal(hit(el,raw,'needle',i)?.toString(),'needle');assert(el.querySelector('strong'));assert(el.querySelector('em'));assert(el.querySelector('del'));});
 test('可见链接文字精确、URL与Markdown标记不猜同词；跨隐藏语法拒绝',()=>{const raw='[needle](https://host/needle) **needle**';const el=render(raw);assert.equal(hit(el,raw,'needle')?.toString(),'needle');assert.equal(hit(el,raw,'needle',1),null);assert.equal(hit(el,raw,'**'),null);assert.equal(hit(el,raw,') **needle'),null);});
 test('引用/嵌套引用/列表/多行续项/任务项与重复表格单元格',()=>{const raw='> 引用 needle\n> > 内层 needle\n\n- 列表 needle\n  续行 needle\n- [x] 任务 needle\n\n| needle | needle |\n|---|---|\n| needle | needle |';const el=render(raw);for(let i=0;i<9;i++)assert.equal(hit(el,raw,'needle',i)?.toString(),'needle','occurrence '+i);});
 test('围栏/缩进代码内相同词不和正文混淆，代码标签/围栏不可定位',()=>{const raw='正文 needle\n\n```js\nneedle\nneedle\n```\n\n    needle\n';const el=render(raw);for(let i=0;i<4;i++)assert.equal(hit(el,raw,'needle',i)?.toString(),'needle');assert.equal(hit(el,raw,'```'),null);assert.equal(hit(el,raw,'js'),null);});
 test('Obsidian高亮与wiki别名保留映射，生成目标URL不可定位',()=>{const raw='==needle== [[target|needle]] [[needle#Heading]]';const el=render(raw);for(let i=0;i<3;i++)assert.equal(hit(el,raw,'needle',i)?.toString(),'needle');assert.equal(hit(el,raw,'target'),null);assert.equal(hit(el,raw,'Heading'),null);});
 test('脚注摘除和DOCTYPE删除之后正文的原CRLF偏移仍可信',()=>{const raw='needle\r\n\r\n[^a]: 定义 needle\r\n\r\n<!DOCTYPE html>\r\n\r\n正文 needle';const el=render(raw);assert.equal(hit(el,raw,'needle')?.toString(),'needle');assert.equal(hit(el,raw,'needle',1),null);assert.equal(hit(el,raw,'needle',2)?.toString(),'needle');});
 test('实体/转义与多UTF16字符映射，HTML属性不伪造定位',()=>{const raw='&amp; &#128512; \\* needle <span data-preview-map="needle">needle</span>';const el=render(raw);assert.equal(hit(el,raw,'&amp;')?.toString(),'&');assert.equal(hit(el,raw,'&#128512;')?.toString(),'😀');assert.equal(hit(el,raw,'needle')?.toString(),'needle');assert.equal(hit(el,raw,'needle',1),null);assert.equal(hit(el,raw,'needle',2)?.toString(),'needle');assert.equal(hit(el,raw,'amp'),null);});
 test('代码高亮修改文本节点后仍按该code的原文映射，不包含复制控件',()=>{w.hljs={highlightElement:el=>{el.innerHTML='<span class="hljs-keyword">needle</span>\n';}};const raw='```js\nneedle\n```';const el=render(raw);assert.equal(hit(el,raw,'needle')?.toString(),'needle');assert(!el.querySelector('.code-copy')?.hasAttribute('data-preview-map'));delete w.hljs;});
 test('旧根/新根/同词正文互不串映射，无效范围及未知插件可拒绝',()=>{const raw='needle',a=render(raw),b=render('other needle');assert.equal(w.PreviewLocation.locate(a,0,6)?.toString(),'needle');assert.equal(w.PreviewLocation.locate(b,0,6)?.toString(),'other ');assert.equal(w.PreviewLocation.locate(a,-1,6),null);assert.equal(w.PreviewLocation.locate(a,0,100),null);const other=w.document.createElement('div');other.textContent=raw;assert.equal(w.PreviewLocation.locate(other,0,6),null);});
 test('转义表格分隔符不将同词串到相邻单元格',()=>{for(const raw of ['| needle \\| needle | needle |\n|---|---|\n| needle | needle |','| needle \\\\| needle |\n|---|---|\n| needle | needle |']){const el=render(raw);const count=raw.match(/needle/g).length;for(let i=0;i<count;i++)assert.equal(hit(el,raw,'needle',i)?.toString(),'needle');assert.equal(hit(el,raw,'| needle',2),null);}});
 test('围栏开头空行保留原偏移，隐藏HTML正文不假报定位',()=>{const raw='```txt\n\nneedle\n```\n\n正文 <span hidden>needle</span> needle';const el=render(raw);assert.equal(hit(el,raw,'needle')?.toString(),'needle');assert.equal(hit(el,raw,'needle',1),null);assert.equal(hit(el,raw,'needle',2)?.toString(),'needle');});
 test('20万字符正文和代码映射没有参数展开栈溢出，末尾命中仍精确',()=>{for(const raw of ['a'.repeat(200000)+' needle','```txt\n'+'a'.repeat(200000)+' needle\n```']){const el=render(raw);assert.equal(hit(el,raw,'needle')?.toString(),'needle');}});
 console.log('预览映射：'+passed+' 通过 / 0 失败');
}finally{w.close();}
