const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const {JSDOM}=require('jsdom'); const root=path.resolve(__dirname,'..'),P='C:/project',key='myide-session:'+P;
const tick=()=>new Promise(r=>setImmediate(r));
const deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};};
let passed=0;
function fixture(state) {
  const dom=new JSDOM('<head></head><body><footer id="statusbar"></footer><div id="modal-mask"></div></body>',{url:'https://fixture.test',runScripts:'outside-only'}),w=dom.window,calls=[],notices=[];
  Object.defineProperty(w.navigator,'platform',{value:'Win32'});
  if(state!==undefined)w.localStorage.setItem(key,typeof state==='string'?state:JSON.stringify(state));
  w.App={root:P,getTool:()=> 'project',setTool:t=>calls.push(['tool',t])};
  w.Tree={getExpandedPaths:()=>[P+'/dir'],setExpandedPaths:p=>calls.push(['expanded',p])};
  w.MI={toast:s=>notices.push(s),copyText:async s=>calls.push(['copy',s])};
  w.Viewer={openTabs:[],activeTab:null,addLazyTab(p,opts){if(this.openTabs.some(t=>w.DocumentPaths.key(t.path)===w.DocumentPaths.key(p)))return;this.openTabs.push({path:p,lazy:true,scrollTop:opts.scrollTop,restoreLine:opts.line,pinned:opts.pinned});w.Session.save();},activate(i){this.activeTab=this.openTabs[i];this.activeTab.lazy=false;this.activeTab.mode='edit';calls.push(['activate',this.activeTab.path]);},revealLine:l=>calls.push(['line',l])};
  w.Modal={stack:[],show:box=>{w.document.getElementById('modal-mask').append(box);w.Modal.stack.push(box);},hide:()=>{const box=w.Modal.stack.pop();box?.remove();box?.onModalHide?.();},confirm:async()=>true};
  for(const p of ['document-paths.js','session.js'])w.eval(fs.readFileSync(path.join(root,'renderer',p),'utf8'));
  return {w,calls,notices,read:()=>w.localStorage.getItem(key),close:()=>w.close()};
}
async function test(name,state,fn){const f=fixture(state);try{await fn(f);passed++;console.log('ok '+name);}finally{f.close();}}
const plain=x=>JSON.parse(JSON.stringify(x));
const button=(f,label)=>[...f.w.document.querySelectorAll('.session-recovery button')].find(b=>b.textContent===label);
(async()=>{
 await test('坏标签不阻断合法标签、活动位置、展开与工具，后台不读盘',{tabs:[{},P+'/a',{p:P+'/b',s:22,l:3,f:true}],active:P+'/b',expanded:[P+'/dir'],tool:'outline'},async f=>{
  const before=f.read(),r=await f.w.Session.restore();assert.equal(r.status,'partial');assert.equal(r.entries.length,2);assert.equal(r.entries[0].status,'pending');assert.equal(r.entries[1].status,'loaded');assert(f.calls.some(c=>c[0]==='line'&&c[1]===3));assert(f.calls.some(c=>c[0]==='tool'&&c[1]==='outline'));assert(f.calls.some(c=>c[0]==='expanded'));assert.equal(f.w.Session.saveNow().protected,true);assert.equal(f.read(),before);assert(!f.w.document.getElementById('session-recovery-status').hidden);
 });
 await test('坏JSON反馈且自动/立即保存都保留原字符串','{broken',async f=>{const r=await f.w.Session.restore();assert(r.blocked);assert.equal(r.errors.length,1);f.w.Session.save();assert(f.w.Session.saveNow().protected);assert.equal(f.read(),'{broken');assert(f.notices.length);});
 await test('拒绝邻居项目、相对路径、点段、NUL和无效展开，合法项继续',{tabs:['C:/project2/a','relative',P+'/../other/a',P+'/nul\0',P+'/valid'],active:'C:/project2/a',expanded:[P+'/dir','C:/project2/dir'],tool:'outline'},async f=>{const r=await f.w.Session.restore();assert.deepEqual(plain(f.w.Viewer.openTabs.map(t=>t.path)),[P+'/valid']);assert(r.errors.length>=6);assert.deepEqual(plain(f.calls.find(c=>c[0]==='expanded')[1]),[P+'/dir']);assert(!f.calls.some(c=>c[0]==='activate'));});
 await test('滚动/行号坏值按默认恢复并留下原因，固定值仅真布尔生效',{tabs:[{p:P+'/a',s:-1,l:1.2,f:'true'},{p:P+'/b',s:20,l:2,f:true}],active:null},async f=>{const r=await f.w.Session.restore();assert.equal(r.errors.length,2);assert.equal(f.w.Viewer.openTabs[0].scrollTop,0);assert(!f.w.Viewer.openTabs[0].pinned);assert(f.w.Viewer.openTabs[1].pinned);});
 await test('路径大小写/分隔符重复只登记一次，旧路径数组兼容',{tabs:[P+'/a','c:\\PROJECT\\a',P+'/b'],active:P+'/a'},async f=>{const r=await f.w.Session.restore();assert.equal(r.status,'ready');assert.equal(f.w.Viewer.openTabs.length,2);assert.equal(r.entries[1].status,'pending');});
 await test('活动文件在列表之外仍懒登记后打开，顺序保留',{tabs:[P+'/a',P+'/b'],active:P+'/c'},async f=>{await f.w.Session.restore();assert.deepEqual(plain(f.w.Viewer.openTabs.map(t=>t.path)),[P+'/a',P+'/b',P+'/c']);assert.equal(f.w.Viewer.activeTab.path,P+'/c');});
 await test('读取失败保留标签且不阻断目录/工具恢复',{tabs:[P+'/a',P+'/b'],active:P+'/a',expanded:[P+'/dir'],tool:'outline'},async f=>{f.w.Viewer.activate=function(i){this.activeTab=this.openTabs[i];this.activeTab.error='ENOENT';this.activeTab.mode='error';};const r=await f.w.Session.restore();assert(r.blocked);assert.equal(r.entries[0].status,'failed');assert.equal(f.w.Viewer.openTabs.length,2);assert(f.calls.some(c=>c[0]==='tool'));});
 await test('一个addLazyTab异常不妨碍其余标签和工具',{tabs:[P+'/a',P+'/b'],active:P+'/b',tool:'outline'},async f=>{const add=f.w.Viewer.addLazyTab;f.w.Viewer.addLazyTab=function(p,o){if(p.endsWith('/a'))throw Error('injected');return add.call(this,p,o);};const r=await f.w.Session.restore();assert.equal(r.entries[0].status,'failed');assert.equal(r.entries[1].status,'loaded');assert(f.calls.some(c=>c[0]==='tool'));});
 await test('旧项目加载迟到不定位/展开/改工具，新项目记录不被旧定时器写入',{tabs:[{p:P+'/a',l:8}],active:P+'/a',expanded:[P+'/dir'],tool:'outline'},async f=>{const gate=deferred(),activate=f.w.Viewer.activate;f.w.Viewer.activate=function(i){activate.call(this,i);this.activeTab.loadPromise=gate.promise;};const pending=f.w.Session.restore();await tick();f.w.App.root='C:/other';f.w.Viewer.activeTab={path:'C:/other/b',mode:'edit'};gate.resolve();const r=await pending;assert.equal(r.status,'stale');assert(!f.calls.some(c=>['line','tool','expanded'].includes(c[0])));assert.equal(f.w.localStorage.getItem('myide-session:C:/other'),null);});
 await test('同项目新恢复轮胜出，旧加载结算返回stale不污染新报告',{tabs:[P+'/a'],active:P+'/a',tool:'outline'},async f=>{const gate=deferred(),activate=f.w.Viewer.activate;let first=true;f.w.Viewer.activate=function(i){activate.call(this,i);this.activeTab.loadPromise=first?gate.promise:Promise.resolve();first=false;};const old=f.w.Session.restore();await tick();const fresh=await f.w.Session.restore();gate.resolve();const r=await old;assert.equal(r.status,'stale');assert.equal(f.w.Session.getRestoreReport().status,fresh.status);assert.equal(f.calls.filter(c=>c[0]==='tool').length,1);});
 await test('恢复在途或记录被外部替换时不覆盖/不应用旧工具',{tabs:[P+'/a'],active:P+'/a',tool:'outline'},async f=>{const gate=deferred();f.w.Viewer.activate=function(i){this.activeTab=this.openTabs[i];this.activeTab.loadPromise=gate.promise;};const old=f.w.Session.restore();await tick();assert(f.w.Session.saveNow().protected);f.w.localStorage.setItem(key,'{"tabs":[]}');gate.resolve();const r=await old;assert(r.blocked);assert(!f.calls.some(c=>c[0]==='tool'));assert.equal(f.read(),'{"tabs":[]}');});
 await test('延迟保存绑定发起项目并核对原版本',{tabs:[]},async f=>{f.w.Viewer.openTabs=[{path:P+'/a',mode:'edit'}];f.w.Session.save();f.w.App.root='C:/other';await new Promise(r=>setTimeout(r,450));assert.equal(f.w.localStorage.getItem('myide-session:C:/other'),null);assert.equal(f.read(),'{"tabs":[]}');f.w.App.root=P;f.w.Session.save();f.w.localStorage.setItem(key,'external');await new Promise(r=>setTimeout(r,450));assert.equal(f.read(),'external');assert(f.notices.some(n=>n.includes('记录已变化')));});
 await test('保存使用路径段归属，当前活动光标与dirty/临时页独立',{tabs:[]},async f=>{const a={path:P+'/a',mode:'edit'},b={path:'C:/project2/b'},c={path:P+'/c',dirty:true},d={path:P+'/d',retention:'preview'};f.w.Viewer.openTabs=[a,b,c,d];f.w.Viewer.activeTab=a;f.w.Viewer.cm={view:{state:{selection:{main:{head:7}},doc:{lineAt:()=>({number:4})}}}};assert(f.w.Session.saveNow().ok);const s=JSON.parse(f.read());assert.deepEqual(s.tabs.map(t=>t.p),[P+'/a']);assert.equal(s.tabs[0].l,4);assert.equal(s.active,P+'/a');});
 await test('详情文本安全、键盘取消与焦点返回、复制原记录','{broken <img src=x>',async f=>{await f.w.Session.restore();const status=f.w.document.getElementById('session-recovery-status');status.focus();status.click();assert.equal(f.w.document.querySelectorAll('.session-recovery img').length,0);button(f,'复制原记录').click();await tick();assert(f.calls.some(c=>c[0]==='copy'&&c[1]===f.read()));f.w.document.activeElement.dispatchEvent(new f.w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));assert(!f.w.document.querySelector('.session-recovery'));assert.equal(f.w.document.activeElement,status);});
 await test('明确确认后先备份核对再保存，备份可从状态栏复制','{broken',async f=>{await f.w.Session.restore();f.w.Session.showRestoreReport();button(f,'备份原记录并保存当前会话').click();await tick();assert.deepEqual(JSON.parse(f.read()).tabs,[]);const backups=Object.keys(f.w.localStorage).filter(k=>k.startsWith('myide-session-backup:'));assert.equal(backups.length,1);assert.equal(f.w.localStorage.getItem(backups[0]),'{broken');assert(!f.w.Session.getRestoreReport().blocked);f.w.document.getElementById('session-recovery-status').click();button(f,'复制原记录').click();await tick();assert(f.calls.some(c=>c[0]==='copy'&&c[1]==='{broken'));});
 await test('取消/备份写失败/确认后换项目都保留唯一原记录','{broken',async f=>{await f.w.Session.restore();f.w.Modal.confirm=async()=>false;f.w.Session.showRestoreReport();button(f,'备份原记录并保存当前会话').click();await tick();assert.equal(f.read(),'{broken');f.w.Modal.confirm=async()=>true;const proto=Object.getPrototypeOf(f.w.localStorage),write=proto.setItem;proto.setItem=function(k,v){if(k.startsWith('myide-session-backup:'))throw Error('quota');return write.call(this,k,v);};button(f,'备份原记录并保存当前会话').click();await tick();assert.equal(f.read(),'{broken');assert(f.w.Session.getRestoreReport().blocked);proto.setItem=write;f.w.Modal.confirm=async()=>{f.w.App.root='C:/other';return true;};button(f,'备份原记录并保存当前会话').click();await tick();assert.equal(f.read(),'{broken');});
 await test('重新读取会话后仍能回看/复制各份原记录备份','{broken',async f=>{await f.w.Session.restore();f.w.Session.showRestoreReport();button(f,'备份原记录并保存当前会话').click();await tick();await f.w.Session.restore();const status=f.w.document.getElementById('session-recovery-status');assert(!status.hidden);assert.equal(status.textContent,'会话记录备份');status.click();button(f,'复制备份 1').click();await tick();assert(f.calls.some(c=>c[0]==='copy'&&c[1]==='{broken'));});
 await test('已有搜索和启动工具名称仍可恢复，未知名称留诊断',{tabs:[],tool:'search'},async f=>{assert.equal((await f.w.Session.restore()).status,'ready');assert(f.calls.some(c=>c[0]==='tool'&&c[1]==='search'));f.w.localStorage.setItem(key,JSON.stringify({tabs:[],tool:'launch'}));assert.equal((await f.w.Session.restore()).status,'ready');f.w.localStorage.setItem(key,JSON.stringify({tabs:[],tool:'unknown'}));assert((await f.w.Session.restore()).blocked);});
 await test('关闭最后项目后旧恢复入口隐藏，不把空会话写回旧项目','{broken',async f=>{await f.w.Session.restore();f.w.Session.save();f.w.App.root=null;await tick();assert(f.w.document.getElementById('session-recovery-status').hidden);assert.equal(f.read(),'{broken');});
 console.log('会话恢复：'+passed+' 通过 / 0 失败');
})().catch(e=>{console.error(e.stack);process.exitCode=1;});
