const { app, BrowserWindow, dialog } = require('electron');
const fs = require('fs'), path = require('path'), os = require('os'), assert = require('assert/strict');
const { start } = require('../tests/fixtures/remote-ssh');
const home = fs.mkdtempSync(path.join(os.tmpdir(), 'myide-remote-ui-')), output = path.join(__dirname, '..', '.ui-check-trash', 'remote-' + process.pid);
const remote = path.join(home, 'server'), local = path.join(home, 'local'), download = path.join(home, 'downloads');
for (const p of [remote, local, download, output]) fs.mkdirSync(p, { recursive: true });
fs.mkdirSync(path.join(remote, '中文目录')); fs.writeFileSync(path.join(remote, 'server.txt'), '服务器文件\n');
const content = Buffer.from('本地上传内容\n'.repeat(4096)); fs.writeFileSync(path.join(local, 'upload.txt'), content);
os.homedir = () => home; app.setPath('userData', path.join(home, 'profile')); process.argv.push('--headless');
let win, server, passed = 0, prompts = 0; const errors = [];
const nativeDialog = dialog.showMessageBox.bind(dialog);
dialog.showMessageBox = async (...args) => { const options = args.at(-1); if (options.title === '确认服务器指纹' && options.detail.startsWith('127.0.0.1:')) { prompts++; return { response: 1 }; } return nativeDialog(...args); };
const sleep = ms => new Promise(r => setTimeout(r, ms)), probe = async source => { try { return await win.webContents.executeJavaScript(source, true); } catch (e) { throw Error(e.message + '\n脚本：' + source + '\n控制台：' + errors.join('\n')); } };
const check = (name, value) => { assert(value, name); passed++; console.log('ok ' + name); };
const wait = async source => { for (let n = 0; n < 350; n++) { if (await probe(source)) return; await sleep(30); } throw Error('等待失败：' + source + '\n' + await probe('document.getElementById("remote-notice").textContent')); };
const snapshot = async name => { win.webContents.invalidate(); await win.webContents.capturePage(); await sleep(250); fs.writeFileSync(path.join(output, name + '.png'), (await win.webContents.capturePage()).toPNG()); };
require('../main');
app.whenReady().then(async () => {
  try {
    server = await start(remote);
    for (let n = 0; n < 100 && !BrowserWindow.getAllWindows().length; n++) await sleep(50);
    win = BrowserWindow.getAllWindows()[0]; win.webContents.on('console-message', (_e, level, message) => { if (level >= 3) errors.push(message); });
    await wait('!!window.App&&!!window.RemotePanel&&!!window.myIDE?.remote'); win.setContentSize(1280, 850);
    await probe('document.getElementById("tool-remote").click(); window.remoteEvents=[]; myIDE.remote.onEvent(e=>remoteEvents.push(e)); undefined;');
    check('真实实例隐藏且工具可进入', !win.isVisible() && await probe('App.getTool()==="remote"&&!document.getElementById("remote-main").classList.contains("hidden")'));
    await snapshot('welcome-dark');
    await probe('document.getElementById("remote-welcome-add").click()');
    check('密码输入遮罩且密码认证隐藏私钥字段', await probe('(()=>{const f=document.querySelector(".remote-form form");return f.elements.password.type==="password"&&getComputedStyle(f.elements.privateKey.closest("label")).display==="none"})()'));
    await snapshot('connection-form-dark');
    await probe(`(()=>{const f=document.querySelector('.remote-form form');const values=${JSON.stringify({ name: '本地验证服务器', host: '127.0.0.1', port: server.port, username: 'fixture', password: 'fixture-secret' })};for(const [key,value] of Object.entries(values))f.elements[key].value=value;f.elements.remember.checked=true;f.requestSubmit()})()`);
    await wait('!document.querySelector(".remote-form")&&document.querySelectorAll(".remote-profile").length===1');
    check('真实safeStorage保存密码无明文', !fs.readFileSync(path.join(home, '.myide', 'remote.json'), 'utf8').includes('fixture-secret'));
    await probe('document.getElementById("remote-connect").click()');
    await wait('document.querySelectorAll(".remote-terminal .xterm").length===1&&!document.getElementById("remote-new-terminal").disabled&&remoteEvents.some(e=>e.type==="terminal-data")');
    check('真实主进程IPC首次指纹核对且xterm已加载', prompts === 1 && await probe('!!window.Terminal&&!!window.FitAddon'));
    await probe('document.getElementById("remote-new-terminal").click()'); await wait('document.querySelectorAll(".remote-terminal .xterm").length===2&&new Set(remoteEvents.filter(e=>e.type==="terminal-data").map(e=>e.terminalId)).size===2');
    check('多终端标签保持两个真实SSH Shell', server.shells.length === 2);
    await probe('document.querySelector(".remote-terminal:not(.hidden) .xterm-helper-textarea").dispatchEvent(new KeyboardEvent("keydown",{key:"c",code:"KeyC",keyCode:67,which:67,ctrlKey:true,bubbles:true}))');
    await sleep(80); check('终端Ctrl+C通过xterm送往服务器', server.shells[1].input.includes('\x03'));
    await snapshot('terminal-dark');
    await probe('document.getElementById("remote-tab-files").click()'); await wait('document.querySelectorAll("#remote-remote-pane [data-path]").length===2');
    const setPath = async (side, target) => { await probe(`(()=>{const f=document.querySelector('#remote-${side}-pane form');f.querySelector('input').value=${JSON.stringify(target)};f.requestSubmit()})()`); await wait(`document.querySelector('#remote-${side}-pane input').value===${JSON.stringify(target)}&&document.querySelector('#remote-${side}-pane .remote-file-status').textContent.includes('项')`); };
    await setPath('local', local);
    await probe('document.querySelector("#remote-local-pane [data-path]").click();document.querySelector("#remote-local-pane [data-action=upload]").click()');
    await wait('remoteEvents.some(e=>e.type==="transfer"&&e.job.direction==="upload"&&e.job.state==="completed")'); check('UI选择本地文件后通过真实SFTP上传', fs.readFileSync(path.join(remote, 'upload.txt')).equals(content));
    await setPath('local', download); await wait('document.querySelectorAll("#remote-remote-pane [data-path]").length===3');
    await probe('Array.from(document.querySelectorAll("#remote-remote-pane [data-path]")).find(e=>e.dataset.path==="/upload.txt").click();document.querySelector("#remote-remote-pane [data-action=download]").click()');
    await wait('remoteEvents.some(e=>e.type==="transfer"&&e.job.direction==="download"&&e.job.state==="completed")'); check('UI下载并显示完成队列', fs.readFileSync(path.join(download, 'upload.txt')).equals(content) && await probe('document.getElementById("remote-transfer-jobs").textContent.includes("已完成")'));
    await wait('document.querySelectorAll("#remote-local-pane [data-path]").length===1&&document.querySelector("#remote-local-pane .remote-file-status").textContent.includes("项")');
    await probe('Array.from(document.querySelectorAll("#remote-remote-pane [data-path]")).find(e=>e.dataset.path==="/中文目录").dispatchEvent(new MouseEvent("dblclick",{bubbles:true}))'); await wait('document.querySelector("#remote-remote-pane input").value==="/中文目录"');
    await probe('document.querySelector("#remote-remote-pane [data-action=up]").click()'); await wait('document.querySelector("#remote-remote-pane input").value==="/"');
    check('目录双击进入且上级返回根目录', true);
    await snapshot('files-dark');
    win.setMinimumSize(640, 480); win.setContentSize(900, 720); await probe('Theme.set("light");for(let n=0;n<4;n++)document.getElementById("sb-tf-inc").click()');
    await sleep(200); check('窄窗大字号文件面板不横向溢出', await probe('(()=>{const e=document.getElementById("remote-main");return e.scrollWidth<=e.clientWidth+1&&[...document.querySelectorAll(".remote-file-pane")].every(p=>p.scrollWidth<=p.clientWidth+1)})()')); await snapshot('files-narrow-light');
    win.setContentSize(1280, 850); await probe('Theme.set("crimson");for(let n=0;n<4;n++)document.getElementById("sb-tf-dec").click()'); await snapshot('files-crimson');
    await probe('document.getElementById("remote-disconnect").click()'); await wait('document.getElementById("remote-new-terminal").disabled');
    check('断开连接禁用远程文件和终端操作', await probe('[...document.querySelectorAll("#remote-remote-pane button")].every(b=>b.disabled)'));
    await probe('document.getElementById("remote-connect").click()'); await wait('!document.getElementById("remote-new-terminal").disabled'); check('再次连接使用已记住指纹', prompts === 1);
    check('无渲染脚本异常', errors.length === 0);
    console.log('远程真实窗口：' + passed + ' 通过 / 0 失败；截图：' + output); await server.close(); app.exit(0);
  } catch (error) { console.error(error); fs.writeFileSync(path.join(output, 'failure.txt'), error.stack); if (win) await snapshot('failure'); app.exit(1); }
});
process.on('exit', () => { if (path.dirname(home) === path.resolve(os.tmpdir()) && path.basename(home).startsWith('myide-remote-ui-')) try { fs.rmSync(home, { recursive: true, force: true }); } catch {} });
setTimeout(() => app.exit(2), 120000).unref();
