const { app, BrowserWindow } = require('electron');
const fs = require('fs'), path = require('path'), os = require('os'), assert = require('assert/strict');
const home = fs.mkdtempSync(path.join(os.tmpdir(), 'myide-startup-check-'));
const output = path.join(__dirname, '..', '.ui-check-trash', 'startup-window-' + process.pid);
fs.mkdirSync(output, { recursive: true }); os.homedir = () => home;
app.setPath('userData', path.join(home, 'profile')); process.argv.push('--headless');
let win, passed = 0; const errors = [];
const sleep = ms => new Promise(r => setTimeout(r, ms));
const probe = source => win.webContents.executeJavaScript(source, true);
const check = (name, value) => { assert(value, name); passed++; console.log('ok ' + name); };
async function wait(source) { for (let n = 0; n < 200; n++) { if (await probe(source)) return; await sleep(50); } throw Error('等待失败：' + source); }
app.on('browser-window-created', (_e, window) => { win = window; win.webContents.on('console-message', (_e, level, message) => { if (level >= 3) errors.push(message); }); });
require('../main');
app.whenReady().then(async () => { try {
  for (let n = 0; !win && n < 100; n++) await sleep(20);
  await wait('!!window.App&&!!window.VendorLoader&&!!document.getElementById("btn-open").onclick');
  check('隐藏窗口启动正常且未加载Office和流程图库', !win.isVisible() && await probe('!window.mermaid&&!window.docxPreview&&!window.XLSX&&!window.pptxPreview'));
  check('启动未加载本地文件栏目录', await probe('document.querySelector("#remote-local-pane input").value===""'));
  check('启动注册数据库IPC时没有加载数据库驱动', !Object.keys(require.cache).some(p => /node_modules[\\/](mysql2|pg|sql\.js)[\\/]/.test(p)));
  await probe(`App.setRoot(${JSON.stringify(home)})`);
  await probe('Theme.set("crimson")');
  await probe('window.startupEditorHost=document.createElement("div");document.getElementById("viewer").appendChild(startupEditorHost);window.startupEditor=MdEditor.create({parent:startupEditorHost,doc:"# live\\n\\n```mermaid\\ngraph TD; C-->D\\n```\\n",onChange:()=>{}});undefined;');
  await wait('!!startupEditorHost.querySelector(".cm-md-mermaid svg")'); check('首次实时预览按需加载流程图', true);
  await probe('window.startupPreview=MI.renderFor({name:"图.md"})({name:"图.md",path:"C:/diagram.md",content:"```mermaid\\ngraph TD; A-->B\\n```"});document.getElementById("viewer").appendChild(startupPreview);undefined;');
  await wait('!!startupPreview.querySelector(".mermaid-box svg")'); check('Markdown预览复用流程图库并生成SVG', true);
  await probe('startupEditor.destroy();startupEditorHost.remove();startupPreview.remove();undefined;');
  const XLSX = require('xlsx'), book = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(book, XLSX.utils.aoa_to_sheet([['启动加载测试']]), 'Sheet1');
  const sheet = path.join(home, 'fixture.xlsx'); fs.writeFileSync(sheet, XLSX.write(book, { type: 'buffer', bookType: 'xlsx' }));
  await probe(`Viewer.openFile(${JSON.stringify(sheet)})`); await wait('document.querySelector("#viewer .sheet-table")?.textContent.includes("启动加载测试")');
  check('首次打开Excel按需加载并显示真实单元格', await probe('!!window.XLSX&&!window.docxPreview&&!window.pptxPreview'));
  const zip = new (require('jszip'))();
  zip.file('[Content_Types].xml', '<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>');
  zip.file('_rels/.rels', '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>');
  zip.file('word/document.xml', '<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body><w:p><w:r><w:t>启动Word预览测试</w:t></w:r></w:p><w:sectPr/></w:body></w:document>');
  const word = path.join(home, 'fixture.docx'); fs.writeFileSync(word, await zip.generateAsync({ type: 'nodebuffer' }));
  await probe(`Viewer.openFile(${JSON.stringify(word)})`); await wait('document.querySelector("#viewer .docx-body")?.textContent.includes("启动Word预览测试")'); check('首次打开Word按需加载并显示真实正文', true);
  await probe('VendorLoader.load("pptx").then(()=>true)'); check('PPT库可按需初始化且不重复加载', await probe('typeof pptxPreview.init==="function"&&document.querySelectorAll("script[src*=pptx-preview]").length===1'));
  const SQL = await require('sql.js')(), database = path.join(home, 'fixture.db'); const db = new SQL.Database(); fs.writeFileSync(database, db.export()); db.close();
  const result = await probe(`(async()=>{const c=await myIDE.db.connect({type:'sqlite',file:${JSON.stringify(database)}});if(!c.ok)return c;const r=await myIDE.db.query(c.data.id,'SELECT 42 AS answer');await myIDE.db.close(c.data.id);return r})()`);
  check('SQLite驱动首次连接仍可执行真实查询', result.ok && result.data.rows[0].answer === 42);
  check('首次加载无渲染异常', errors.length === 0);
  win.webContents.invalidate(); await win.webContents.capturePage(); await sleep(250);
  fs.writeFileSync(path.join(output, 'preview.png'), (await win.webContents.capturePage()).toPNG());
  console.log('启动真实窗口：' + passed + ' 通过 / 0 失败；截图：' + output); app.exit(0);
} catch (e) { console.error(e); fs.writeFileSync(path.join(output, 'failure.txt'), e.stack); if (win) fs.writeFileSync(path.join(output, 'failure.png'), (await win.webContents.capturePage()).toPNG()); app.exit(1); } });
process.on('exit', () => { if (path.dirname(home) === path.resolve(os.tmpdir()) && path.basename(home).startsWith('myide-startup-check-')) try { fs.rmSync(home, { recursive: true, force: true }); } catch {} });
setTimeout(() => app.exit(2), 60000).unref();
