const { app, BrowserWindow, dialog } = require('electron');
const fs = require('fs'), path = require('path'), os = require('os'), assert = require('assert/strict');
const { start } = require('../tests/fixtures/remote-ssh');
const home = fs.mkdtempSync(path.join(os.tmpdir(), 'myide-remote-ui-')), output = path.join(__dirname, '..', '.ui-check-trash', 'remote-' + process.pid);
const remote = path.join(home, 'server'), local = path.join(home, 'local'), download = path.join(home, 'downloads');
for (const p of [remote, local, download, output]) fs.mkdirSync(p, { recursive: true });
fs.mkdirSync(path.join(remote, '中文目录')); fs.writeFileSync(path.join(remote, 'server.txt'), '服务器文件\n');
const content = Buffer.from('本地上传内容\n'.repeat(4096)); fs.writeFileSync(path.join(local, 'upload.txt'), content);
os.homedir = () => home; app.setPath('userData', path.join(home, 'profile')); process.argv.push('--headless');
let win, server, passed = 0, prompts = 0; const errors = [];
const nativeDialog = dialog.showMessageBox.bind(dialog);
dialog.showMessageBox = async (...args) => { const options = args.at(-1); if (options.title === '确认服务器指纹' && options.detail.startsWith('127.0.0.1:')) { prompts++; return { response: 1 }; } return nativeDialog(...args); };
const sleep = ms => new Promise(r => setTimeout(r, ms)), probe = async source => { try { return await win.webContents.executeJavaScript(source, true); } catch (e) { throw Error(e.message + '\n脚本：' + source + '\n控制台：' + errors.join('\n')); } };
const check = (name, value) => { assert(value, name); passed++; console.log('ok ' + name); };
const wait = async source => { for (let n = 0; n < 350; n++) { if (await probe(source)) return; await sleep(30); } throw Error('等待失败：' + source + '\n' + await probe('document.getElementById("remote-notice").textContent')); };
const snapshot = async name => { win.webContents.invalidate(); await win.webContents.capturePage(); await sleep(250); fs.writeFileSync(path.join(output, name + '.png'), (await win.webContents.capturePage()).toPNG()); };
require('../main');
app.whenReady().then(async () => {
  try {
    server = await start(remote);
    for (let n = 0; n < 100 && !BrowserWindow.getAllWindows().length; n++) await sleep(50);
    win = BrowserWindow.getAllWindows()[0]; win.webContents.on('console-message', (_e, level, message) => { if (level >= 3) errors.push(message); });
    await wait('!!window.App&&!!window.RemotePanel&&!!window.myIDE?.remote'); win.setContentSize(1280, 850);
    await probe('document.getElementById("tool-remote").click(); window.remoteEvents=[]; myIDE.remote.onEvent(e=>remoteEvents.push(e)); undefined;');
    check('真实实例隐藏且工具可进入', !win.isVisible() && await probe('App.getTool()==="remote"&&!document.getElementById("remote-main").classList.contains("hidden")'));
    await snapshot('empty-dark');
    await probe('document.getElementById("remote-add").click()');
    check('密码输入遮罩且密码认证隐藏私钥字段', await probe('(()=>{const f=document.querySelector(".remote-form form");return f.elements.password.type==="password"&&getComputedStyle(f.elements.privateKey.closest("label")).display==="none"})()'));
    await snapshot('connection-form-dark');
    await probe(`(()=>{const f=document.querySelector('.remote-form form');const values=${JSON.stringify({ name: '本地验证服务器', host: '127.0.0.1', port: server.port, username: 'fixture', password: 'fixture-secret' })};for(const [key,value] of Object.entries(values))f.elements[key].value=value;f.elements.remember.checked=true;f.requestSubmit()})()`);
    await wait('!document.querySelector(".remote-form")&&document.querySelectorAll(".remote-profile").length===1');
    check('真实safeStorage保存密码无明文', !fs.readFileSync(path.join(home, '.myide', 'remote.json'), 'utf8').includes('fixture-secret'));
    check('选中服务器后工作区留空且顶部连接可用', await probe('document.getElementById("remote-terminal-empty").textContent.trim()===""&&document.getElementById("remote-title").textContent.includes("本地验证服务器")&&!document.getElementById("remote-connect").disabled&&!document.querySelector(".remote-start")'));
    for (const theme of ['dark', 'light', 'pink', 'crimson', 'graphite']) {
      await probe('Theme.set(' + JSON.stringify(theme) + ')');
      check(theme + '主题工作区继承全局配色', await probe('(()=>{const body=getComputedStyle(document.body),main=getComputedStyle(document.getElementById("remote-main")),pane=getComputedStyle(document.getElementById("remote-terminal-panes")),side=getComputedStyle(document.getElementById("panel-remote"));return ["--bg","--text","--text-dim","--bg-panel"].every(key=>main.getPropertyValue(key)===body.getPropertyValue(key)&&side.getPropertyValue(key)===body.getPropertyValue(key))&&main.backgroundColor===pane.backgroundColor})()'));
    }
    win.setContentSize(1820, 1000); await probe('Theme.set("crimson");for(let n=0;n<2;n++)document.getElementById("sb-tf-inc").click()'); await snapshot('saved-server-crimson');
    win.setContentSize(1280, 850); await probe('Theme.set("dark");for(let n=0;n<2;n++)document.getElementById("sb-tf-dec").click()');
    await probe('window.remoteTestTerms=[];window.remoteFitCalls=0;const BaseTerminal=window.Terminal;window.Terminal=class extends BaseTerminal{constructor(options){super(options);remoteTestTerms.push(this)}};const originalFit=FitAddon.FitAddon.prototype.fit;FitAddon.FitAddon.prototype.fit=function(){remoteFitCalls++;return originalFit.call(this)};document.getElementById("remote-connect").click()');
    await wait('document.querySelectorAll(".remote-terminal .xterm").length===1&&!document.getElementById("remote-new-terminal").disabled&&remoteEvents.some(e=>e.type==="terminal-data")');
    check('真实主进程IPC首次指纹核对且xterm已加载', prompts === 1 && await probe('!!window.Terminal&&!!window.FitAddon'));
    await probe('document.getElementById("remote-new-terminal").click()'); await wait('document.querySelectorAll(".remote-terminal .xterm").length===2&&new Set(remoteEvents.filter(e=>e.type==="terminal-data").map(e=>e.terminalId)).size===2');
    check('多终端标签保持两个真实SSH Shell', server.shells.length === 2);
    await snapshot('two-terminals-before-perf');
    await probe('document.fonts.ready.then(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))))');
    const unchanged = await probe('window.remoteFitCalls=0;window.remoteTestThemes=remoteTestTerms.map(t=>t.options.theme);(async()=>{for(let n=0;n<24;n++){document.documentElement.style.setProperty("--remote-perf-unused",String(n));await new Promise(r=>setTimeout(r,8))}await new Promise(r=>setTimeout(r,80));return {fits:remoteFitCalls,themesUnchanged:remoteTestTerms.every((t,i)=>t.options.theme===remoteTestThemes[i])}})()');
    console.log('无关样式变化24次：终端布局计算 '+unchanged.fits+' 次；配色保持 '+unchanged.themesUnchanged);
    check('无关页面样式变化不重绘终端或计算布局', unchanged.fits === 0 && unchanged.themesUnchanged);
    const resizeCount = server.shells.reduce((sum,shell)=>sum+shell.windowChanges.length,0);
    await probe('(async()=>{for(let n=0;n<10;n++){document.querySelectorAll("[data-term]")[n%2].click();await new Promise(r=>setTimeout(r,20))}})()'); await sleep(100);
    check('切换同尺寸终端不重复发送远程窗口变化', server.shells.reduce((sum,shell)=>sum+shell.windowChanges.length,0) === resizeCount);
    win.setContentSize(1400, 900); await sleep(250);
    check('窗口实际变大后PTY列行仍同步', server.shells[1].windowChanges.length > 0 && await probe('remoteTestTerms[1].cols') === server.shells[1].pty.cols && await probe('remoteTestTerms[1].rows') === server.shells[1].pty.rows);
    win.setContentSize(1280, 850); await sleep(150);
    await probe('document.querySelector(".remote-terminal:not(.hidden) .xterm-helper-textarea").dispatchEvent(new KeyboardEvent("keydown",{key:"c",code:"KeyC",keyCode:67,which:67,ctrlKey:true,bubbles:true}))');
    await sleep(80); check('终端Ctrl+C通过xterm送往服务器', server.shells[1].input.includes('\x03'));
    const beforeOutput = server.shells[1].windowChanges.length;
    server.shells[1].stream.write(Buffer.from(('连续输出中文与ANSI颜色\r\n').repeat(5000) + 'REMOTE_BURST_END\r\n'));
    await wait('(()=>{const b=remoteTestTerms[1].buffer.active;for(let i=Math.max(0,b.length-30);i<b.length;i++)if(b.getLine(i).translateToString().includes("REMOTE_BURST_END"))return true;return false})()');
    check('连续5000行输出正常结束且不诱发远程窗口重画', server.shells[1].windowChanges.length === beforeOutput);
    check('顶部三层紧凑且普通连接提示不额外占行', await probe('(()=>{const h=s=>document.querySelector(s).getBoundingClientRect().height;return h(".remote-toolbar")<=57&&h(".remote-workspace-bar")<=41&&h("#remote-terminal-tabs")<=37&&getComputedStyle(document.getElementById("remote-notice")).display==="none"})()'));
    check('侧栏卡片与标题达到方案尺寸', await probe('document.querySelector(".remote-profile").getBoundingClientRect().height<=79&&document.querySelector("#panel-remote>.panel-title").getBoundingClientRect().height<=49'));
    await snapshot('terminal-dark');
    await probe('Theme.set("light")'); await snapshot('terminal-light');
    await probe('Theme.set("crimson")'); await snapshot('terminal-crimson');
    check('新终端主按钮与连接次级按钮明确区分', await probe('document.getElementById("remote-new-terminal").classList.contains("remote-primary")&&!document.getElementById("remote-connect").classList.contains("remote-primary")&&document.getElementById("remote-connect").classList.contains("remote-muted")'));
    check('终端普通文字使用独立浅色且行高舒适', await probe('(()=>{const e=document.querySelector(".remote-terminal:not(.hidden) .xterm-rows"),s=getComputedStyle(e),ui=getComputedStyle(document.getElementById("remote-main"));return parseFloat(s.fontSize)===13&&s.fontFamily.includes("Cascadia Mono")&&s.color!==ui.color})()'));
    await probe('document.getElementById("sb-tf-inc").click()'); await sleep(200);
    check('终端字号跟随用户调节', await probe('parseFloat(getComputedStyle(document.querySelector(".remote-terminal:not(.hidden) .xterm-rows")).fontSize)===14'));
    await probe('document.getElementById("sb-tf-dec").click()'); await sleep(150);
    await probe('document.getElementById("tool-launch").click();Theme.set("light");document.getElementById("sb-tf-inc").click()'); await sleep(80);
    await probe('document.getElementById("tool-remote").click()');
    await wait('remoteTestTerms.every(t=>t.options.fontSize===14&&t.options.theme.background===getComputedStyle(document.getElementById("remote-main")).backgroundColor)');
    check('离开远程页后改变主题字号再返回同步全部终端', true);
    await probe('document.getElementById("sb-tf-dec").click();Theme.set("crimson")'); await sleep(150);
    check('底部清理入口避开全局玩偶', await probe('(()=>{const p=document.getElementById("pet"),b=document.getElementById("remote-clear-transfers");return !p||b.getBoundingClientRect().right+8<=p.getBoundingClientRect().left})()'));
    await probe('Theme.set("dark")');
    await probe('document.getElementById("remote-tab-files").click()'); await wait('document.querySelectorAll("#remote-remote-pane [data-path]").length===2');
    const setPath = async (side, target) => { await probe(`(()=>{const f=document.querySelector('#remote-${side}-pane form');f.querySelector('input').value=${JSON.stringify(target)};f.requestSubmit()})()`); await wait(`document.querySelector('#remote-${side}-pane input').value===${JSON.stringify(target)}&&document.querySelector('#remote-${side}-pane .remote-file-status').textContent.includes('项')`); };
    await setPath('local', local);
    await probe('document.querySelector("#remote-local-pane [data-path]").click();document.querySelector("#remote-local-pane [data-action=upload]").click()');
    await wait('remoteEvents.some(e=>e.type==="transfer"&&e.job.direction==="upload"&&e.job.state==="completed")'); check('UI选择本地文件后通过真实SFTP上传', fs.readFileSync(path.join(remote, 'upload.txt')).equals(content));
    await setPath('local', download); await wait('document.querySelectorAll("#remote-remote-pane [data-path]").length===3');
    await probe('Array.from(document.querySelectorAll("#remote-remote-pane [data-path]")).find(e=>e.dataset.path==="/upload.txt").click();document.querySelector("#remote-remote-pane [data-action=download]").click()');
    await wait('remoteEvents.some(e=>e.type==="transfer"&&e.job.direction==="download"&&e.job.state==="completed")'); check('UI下载并显示完成队列', fs.readFileSync(path.join(download, 'upload.txt')).equals(content) && await probe('document.getElementById("remote-transfer-jobs").textContent.includes("已完成")'));
    await wait('document.querySelectorAll("#remote-local-pane [data-path]").length===1&&document.querySelector("#remote-local-pane .remote-file-status").textContent.includes("项")');
    await probe('Array.from(document.querySelectorAll("#remote-remote-pane [data-path]")).find(e=>e.dataset.path==="/中文目录").dispatchEvent(new MouseEvent("dblclick",{bubbles:true}))'); await wait('document.querySelector("#remote-remote-pane input").value==="/中文目录"');
    await probe('document.querySelector("#remote-remote-pane [data-action=up]").click()'); await wait('document.querySelector("#remote-remote-pane input").value==="/"');
    check('目录双击进入且上级返回根目录', true);
    fs.mkdirSync(path.join(remote, '大目录')); fs.mkdirSync(path.join(remote, '大目录', '末尾目录'));
    server.control.directoryEntries.set('/大目录', Array.from({length:5000},(_,n)=>({filename:n===4999?'末尾目录':'文件-'+String(n).padStart(5,'0')+'.txt',longname:'',attrs:{mode:n===4999?0o40755:0o100644,size:n,mtime:1,atime:1,uid:0,gid:0}})));
    server.control.readDirBatchSize = 128;
    await probe('window.remoteTestRow=(path)=>Array.from(document.querySelectorAll("#remote-remote-pane [data-path]")).find(r=>r.dataset.path===path);undefined;');
    const directoryStarted = performance.now(); await setPath('remote', '/大目录');
    const directoryRows = await probe('document.querySelectorAll("#remote-remote-pane [data-path]").length');
    console.log('5000项目录进入并显示：'+Math.round(performance.now()-directoryStarted)+'ms；实际文件行 '+directoryRows);
    check('5000项目录只渲染可见行且总数完整', directoryRows > 0 && directoryRows < 100 && await probe('document.querySelector("#remote-remote-pane .remote-file-status").textContent.startsWith("5000 项")'));
    await probe('(()=>{window.remoteFirstFile=remoteTestRow("/大目录/文件-00000.txt");remoteFirstFile.click();const l=document.querySelector("#remote-remote-pane .remote-file-list");l.scrollTop=l.scrollHeight;l.dispatchEvent(new Event("scroll"))})()');
    await wait('!!remoteTestRow("/大目录/文件-04998.txt")');
    await probe('(()=>{remoteTestRow("/大目录/文件-04998.txt").dispatchEvent(new MouseEvent("click",{bubbles:true,ctrlKey:true}));const l=document.querySelector("#remote-remote-pane .remote-file-list");l.scrollTop=0;l.dispatchEvent(new Event("scroll"))})()');
    await wait('!!remoteTestRow("/大目录/文件-00000.txt")?.classList.contains("selected")');
    check('滚动可到达末尾且跨可见区域多选保持', await probe('document.querySelector("#remote-remote-pane .remote-file-status").textContent.endsWith("已选 2 项")'));
    await snapshot('large-directory-crimson');
    await probe('(()=>{const l=document.querySelector("#remote-remote-pane .remote-file-list");l.focus();l.dispatchEvent(new KeyboardEvent("keydown",{key:"End",bubbles:true}));})()');
    check('End键能访问虚拟列表最后一项', await probe('document.activeElement.dataset.path==="/大目录/文件-04998.txt"'));
    await probe('document.activeElement.dispatchEvent(new KeyboardEvent("keydown",{key:"Home",bubbles:true}));document.activeElement.dispatchEvent(new KeyboardEvent("keydown",{key:"Enter",bubbles:true}));');
    await wait('document.querySelector("#remote-remote-pane input").value==="/大目录/末尾目录"&&document.querySelector("#remote-remote-pane .remote-file-status").textContent.startsWith("0 项")');
    check('大目录键盘导航仍能进入空目录', true);
    await setPath('remote', '/大目录');
    await snapshot('files-dark');
    win.setMinimumSize(640, 480); win.setContentSize(900, 720); await probe('Theme.set("light");for(let n=0;n<4;n++)document.getElementById("sb-tf-inc").click()');
    await sleep(200); check('窄窗大字号文件面板不横向溢出', await probe('(()=>{const e=document.getElementById("remote-main");return e.scrollWidth<=e.clientWidth+1&&[...document.querySelectorAll(".remote-file-pane")].every(p=>p.scrollWidth<=p.clientWidth+1)})()')); await snapshot('files-narrow-light');
    win.setContentSize(1280, 850); await probe('Theme.set("crimson");for(let n=0;n<4;n++)document.getElementById("sb-tf-dec").click()'); await snapshot('files-crimson');
    await probe('document.getElementById("remote-local-pane").querySelector("[data-action=upload]").click()'); await sleep(100);
    check('操作错误在导航栏显示且可读完整提示', await probe('(()=>{const n=document.getElementById("remote-notice");return n.classList.contains("error")&&getComputedStyle(n).display!=="none"&&n.title.includes("请先选择文件")})()'));
    await snapshot('files-error-crimson');
    await probe('document.getElementById("remote-disconnect").click()'); await wait('document.getElementById("remote-new-terminal").disabled');
    check('断开连接禁用远程文件和终端操作', await probe('[...document.querySelectorAll("#remote-remote-pane button")].every(b=>b.disabled)'));
    await probe('document.getElementById("remote-connect").click()'); await wait('!document.getElementById("remote-new-terminal").disabled'); check('再次连接使用已记住指纹', prompts === 1);
    check('无渲染脚本异常', errors.length === 0);
    console.log('远程真实窗口：' + passed + ' 通过 / 0 失败；截图：' + output); await server.close(); app.exit(0);
  } catch (error) { console.error(error); fs.writeFileSync(path.join(output, 'failure.txt'), error.stack); if (win) await snapshot('failure'); app.exit(1); }
});
process.on('exit', () => { if (path.dirname(home) === path.resolve(os.tmpdir()) && path.basename(home).startsWith('myide-remote-ui-')) try { fs.rmSync(home, { recursive: true, force: true }); } catch {} });
setTimeout(() => app.exit(2), 120000).unref();
